new function bl_djibian_confhome4pgp(), used in bl_djibian_adduser()

diff --git a/bin/bl-djibian b/bin/bl-djibian
--- a/bin/bl-djibian
+++ b/bin/bl-djibian
@@ -142,11 +142,15 @@ OPTIONS:
   -t, --phone NUMBER               "$"User phone number (optional)""
   -p, --password PASSWORD          "$"User password (for current djibian Operating System)""
   -P, --passfrom FILE              "$"Get user password from first line of FILE (eg: fifo, tmpfs, /dev/stdin ...)""
-  -F, --from-pgpid-card            "$"Get user data from OpenPGP ID smartcard (eg: yubikey, nitrokey, ...)""
+  -f, --from-certificate USER-ID   "$"Get user data from OpenPGP ID certificate identified by given [KEY|U4|U5|EMAIL]."" (Not implemented)
+  -F, --from-pgpid-token           "$"Get user data from OpenPGP ID smartcard (eg: yubikey, nitrokey, ...)""
   -v, --verify                     "$"Resume input data for verification""
   -a, --admin                      "$"Enable admin rights (root power through sudo group)""
+
+"$"Please note that --from-pgpid-token and --from-certificate will automaticaly configure user's HOME
+for OpenPGP usages, see: ""$BL_DJIBIAN_NAME confhome4pgp --help
 "
-	local username sname gname bdate bcountry email phone passwd verify="" extragroups fromcard=""
+	local username sname gname bdate bcountry email phone passwd verify="" extragroups fromcard=0 keyfpr
 	extragroups=$BL_DJIBIAN_EXTRA_GROUPS
 	for ((;$#;)) ; do
 		case "$1" in
@@ -166,7 +170,11 @@ OPTIONS:
 				shift ; passwd=$1 ;;
 			-P|--passfrom|--pass-from)
 				shift ; passwd=$( sed 1q < "$1" ) || return 1 ;;
-			-F|--from-pgp-card|--frompgpcard|--from-gpg-card|--fromgpgcard|--from-pgpid-card|--frompgpidcard) fromcard=1 ;;
+			-f|--from-certificate)
+				[[ "${2^^}" =~ ^(0X)?([ABCDEF0-9]{40})$ ]] || { printf "$FUNCNAME: Error: "$"--from-certificate expect a PGP fingerprint (40 xdigits).""\n\n"$"Try '%s --help' for more information"".\n" "$name" >&2 ; return 2 ; }
+				printf "%s: Error: Sorry, option %s not implemented yet.\n" "$FUNCNAME" "$1" >&2 ; return 2
+				shift ; keyfpr=${BASH_REMATCH[2]} ; fromcard=0 ;;
+			-F|--from-pgp-card|--frompgpcard|--from-gpg-card|--fromgpgcard|--from-pgpid-card|--frompgpidcard|--from-pgpid-token) fromcard=1 ; keyfpr="" ;;
 			-v|--verify) verify=1 ;;
 			-a|--admin) extragroups+=",sudo" ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
@@ -185,12 +193,12 @@ OPTIONS:
 
 	local identifier uid ret
 
-	if [[ "$fromcard" ]] ; then
+	if ((fromcard)) ; then
 		local -A cardinfo
 
-		umask 0002 # Because bl_pgpid_token_check may write into /var/share/djibian/keyrings (sticky bit, group 'users')
 		su -l "${SUDO_USER:-$USER}" -c "gpgconf --kill scdaemon" || true
 		bl_pgpid_token_check --no-fetch --aaname cardinfo || return $?
+		gpgconf --kill scdaemon
 
 		email=${cardinfo[pgpid_email]}
 		identifier=${cardinfo[pgpid_id]}
@@ -199,6 +207,7 @@ OPTIONS:
 		gname=$(printf "// substitued by %s" "${identifier:: 6}...")
 		bdate=$(printf "// substitued by %s" "${identifier:: 6}...")
 		bcountry=$(printf "// substitued by %s" "${identifier:: 6}...")
+		keyfpr=${cardinfo[pgpid_Skeyfpr]}
 	fi
 
 	# If username is given as first argument, override username extracted from smartcard
@@ -258,19 +267,66 @@ OPTIONS:
 
 	echo "$passwd" | passwd --stdin "$username" || { ret=$? ; deluser --stdoutmsglevel=info "$username" ; return $ret ; }
 
-	if [[ "$fromcard" ]] ; then
-		# Try configuring its ~/.gnupg/ with its ownertrust set to ultimate
-		mkdir /home/$identifier/.gnupg /home/$identifier/.ssh
-		chmod go-rwx /home/$identifier/.gnupg /home/$identifier/.ssh
-		gpgconf --kill scdaemon
-		bl_pgpid_token_check --homedir "/home/$identifier/.gnupg" || true
-		gpgconf --homedir "/home/$identifier/.gnupg" --kill scdaemon
-		chown -hR "$username:$username" "/home/$identifier"
-		su -l "$username" -c "gpg --quick-set-ownertrust ${cardinfo[pgpid_Skeyfpr]} ultimate" || true
-		su -l "$username" -c "gpg --export-ssh-key ${cardinfo[pgpid_Skeyfpr]} > /home/$identifier/.ssh/authorized_keys" || true
+	if ((fromcard)) ; then
+		su -l "$username" -c "'$(readlink -f $BASH_SOURCE)' confhome4pgp $keyfpr" || true
 	fi
 
 	printf "$FUNCNAME: Notice: "$"user %s (%s) successfully added to current system"".\n" "$username" "$identifier" >&2
+}
+
+bl_djibian_confhome4pgp()
+{
+	local name
+	((BL_DJIBIAN_isprogram)) && name="$BL_DJIBIAN_NAME ${FUNCNAME:11}" || name="$FUNCNAME"
+	local usage="Usage: $name [KEYFPR]"
+	local helpmsg="
+"$"Reconfigure HOME directory for djibian's OpenPGP usage:""
+- '~/.config/systemd/user': "$"Force SSH_AUTH_SOCK to use gpg-agent (crazy systemd workaround).""
+"$"And if a key fingerprint [KEYFPR] is passed as argument:""
+- '\$GNUPGHOME': "$"Set KEYFPR as the GnuPG's default-key.""
+- '\$GNUPGHOME': "$"Set KEYFPR as the only one ultimate key (downgrading other trust ultimate -> full).""
+- '~/.ssh': "$"Set last usable OpenPGP authentication key as the only one authorized key for ssh login.""
+"
+	local fromcard=0 ret=0
+	for ((;$#;)) ; do
+		case "$1" in
+			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
+			-V|--version) printf "%s %s\n" "$FUNCNAME" "$BL_DJIBIAN_VERSION" ; return ;;
+			--) shift ; break ;;
+			-*) printf "$FUNCNAME: Error: "$"Unrecognized option"" '$1'.\n\n"$"Try '%s --help' for more information"".\n" "$name" >&2 ; return 2 ;;
+			*) break ;;
+		esac
+		shift
+	done
+
+	if [[ -f /usr/lib/systemd/user/gpg-agent.socket ]] ; then
+		mkdir --parents ~/.config/systemd/user/sockets.target.wants || return $?
+		cp --verbose --force /usr/lib/systemd/user/gpg-agent.socket ~/.config/systemd/user/sockets.target.wants >&2 || return $?
+	else
+		printf "$FUNCNAME: Notice: "$"%s is missing. "$"Did you get rid of systemd ?""\n" "'/usr/lib/systemd/user/gpg-agent.socket'" >&2
+	fi
+
+	[[ "$1" ]] || return 0
+
+	[[ "${1^^}" =~ ^(0X)?([ABCDEF0-9]{40})$ ]] || { printf "$FUNCNAME: Error: "$"Argument must be a PGP fingerprint (40 xdigits).""\n\n"$"Try '%s --help' for more information"".\n" "$name" >&2 ; return 2 ; }
+	local key keyfpr=${BASH_REMATCH[2]}
+
+	printf "$FUNCNAME: Info: "$"Check directories and %s certificate.""..\n" "$keyfpr" >&2
+	mkdir -p "${GNUPGHOME:-~/.gnupg}" ~/.ssh || return $?
+	chmod go-rwx "${GNUPGHOME:-~/.gnupg}" ~/.ssh || return $?
+	gpg --list-key 0x$keyfpr || gpg --recv-key 0x$keyfpr || return $?
+
+	printf "$FUNCNAME: Info: "$"Set %s as the GnuPG's default-key"" (${GNUPGHOME:-~/.gnupg})...\n" "$keyfpr" >&2
+	echo "default-key:0:\"$keyfpr" | gpgconf --change-options gpg >&2 || return $?
+
+	printf "$FUNCNAME: Info: "$"Set %s as the only one ultimate key"" (${GNUPGHOME:-~/.gnupg})...\n" "$keyfpr" >&2
+	for key in $(gpg --export-ownertrust | awk -F: '/:6:/ {print $1} ') ; do
+		gpg --quick-set-ownertrust "$key" full || return $?
+	done
+	gpg --quick-set-ownertrust "$keyfpr" ultimate || return $?
+
+	printf "$FUNCNAME: Info: "$"Set last usable OpenPGP authentication key as the only one authorized key for ssh login.""..\n" >&2
+	gpg --export-ssh-key "$keyfpr" > $HOME/.ssh/authorized_keys
 }
 
 bl_djibian_admins()
