WIP bl-foopgp:
* rename fonctions
* 2 new functions: _bl_foopgp_dateISO8601toFR() and bl_foopgp_qiftobash()
* rewrite bl_foopgp_qiftoflow()

diff --git a/bin/bl-foopgp b/bin/bl-foopgp
--- a/bin/bl-foopgp
+++ b/bin/bl-foopgp
@@ -103,7 +103,7 @@ _bl_foopgp_todecnum() {
 	sed 's/.\{2\}$/,&/' <<<"$in"
 }
 
-_bl_foopgp_dateFR2ISO8601() {
+_bl_foopgp_dateFRtoISO8601() {
 	local in
 	(($#)) && in=$@ || read in
 	in=$(sed  's,[^0-9],,g' <<<"$in")
@@ -111,21 +111,77 @@ _bl_foopgp_dateFR2ISO8601() {
 	echo "${in:4:4}-${in:2:2}-${in::2}"
 }
 
+_bl_foopgp_dateISO8601toFR() {
+	local in
+	(($#)) && in=$@ || read in
+	in=$(sed  's,[^0-9],,g' <<<"$in")
+	((${#in}==8)) || printf "%s: Error: Invalid date %s.\n" "$FUNCNAME" "$in" >&2
+	echo "${in:6:2}/${in:4:2}/${in::4}"
+}
+
 ### public functions / program actions ###
 
-bl_foopgp_qif2flow() {
+bl_foopgp_qiftobash() {
+	local name
+	((BL_FOOPGP_isprogram)) && name="$BL_FOOPGP_NAME ${FUNCNAME:3}" || name="$FUNCNAME"
+	local usage="Usage: $name FILE.qif ..."
+	local helpmsg="
+Convert each qif entry to a  \"declare -A ...\" statement to be loaded with eval
+"
+	local path=${PWD}
+	for ((;$#;)) ; do
+		case "$1" in
+			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
+			-V|--version) echo "$FUNCNAME $BL_FOOPGP_VERSION" ; return ;;
+			--) shift ; break ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
+			*) break ;;
+		esac
+		shift
+	done
+	(($#)) || { printf "%s: Error: missing argument\nTry '%s --help' for more information.\n" "$FUNCNAME" "$name" >&2 ; return 2 ; }
+
+	local typ fqif qiffd line
+	local -A entry
+
+	for fqif in "$@" ; do
+		typ="undefined"
+		exec {qiffd}<"$fqif"
+		while read line <&${qiffd} ; do
+			line=${line%$'\r'}  # Remove eventual CR character
+			if [[ ${line,,} =~ "!type:" ]]
+			then
+				typ=${line:6}
+			elif [[ ${line::1} == "!" ]] || [[ -z ${line} ]] # Skip comment or empty line
+			then
+				continue
+			elif [[ ${line::1} != "^" ]]
+			then
+				entry[${line::1}]=${line:1}
+			else
+				entry[type]=${typ}
+				declare -p entry
+				unset entry
+				local -A entry
+			fi
+		done
+		exec {qiffd}<&-
+	done
+}
+
+bl_foopgp_qiftoflow() {
 	local name
 	((BL_FOOPGP_isprogram)) && name="$BL_FOOPGP_NAME ${FUNCNAME:3}" || name="$FUNCNAME"
 	local usage="Usage: $name [OPTIONS] FILE.qif ..."
 	local helpmsg="
 Parse qif file, and ask some questions for each entries to manage foopgp tockens, expenses, inventory....
 Options:
-  -p, --path PATH      Set the path to the account dir (default: assume input files are in)
+  -p, --path PATH      Set the path to the account dir (default: assume input files are in current dir)
 "
-	local path
+	local path=${PWD}
 	for ((;$#;)) ; do
 		case "$1" in
-			-p|--path) shift ; path="$1" ; printf "%s: Warning: --path not implemented.\n" "$FUNCNAME" >&2 ;;
+			-p|--path) shift ; path="$1" ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
 			-V|--version) echo "$FUNCNAME $BL_FOOPGP_VERSION" ; return ;;
 			--) shift ; break ;;
@@ -137,114 +193,106 @@ Options:
 	(($#)) || { printf "%s: Error: missing argument\nTry '%s --help' for more information.\n" "$FUNCNAME" "$name" >&2 ; return 2 ; }
 
 	local -a subaccounts etypes rtypes flow
-	local fqif qiffd flowfd line rectify i=0 j k
+	local fqif flowfd line rectify i=0 j k
 	local remain direction countdec isub1 ityp typ srcdest
 	local -A entry
 
+	mapfile -t subaccounts < <( sed 's,#.*,, ; s,[[:space:]]*$,, ; /^[[:space:]]*$/d ' "$path/subaccounts.list")
+	mapfile -t etypes < <( sed 's,#.*,, ; s,[[:space:]]*$,, ; /^[[:space:]]*$/d ' "$path/expense_types.list")
+	mapfile -t rtypes < <( sed 's,#.*,, ; s,[[:space:]]*$,, ; /^[[:space:]]*$/d ' "$path/revenue_types.list")
+	( [[ "${subaccounts#*:}" ]] && [[ "${etypes#*:}" ]] && [[ "${rtypes#*:}" ]] ) || return 2
+
 	for fqif in "$@" ; do
-		path="$(readlink -f "$(dirname "$fqif")"/../../../..)"
-		mapfile -t subaccounts < <( sed 's,#.*,, ; s,[[:space:]]*$,, ; /^[[:space:]]*$/d ' "$path/subaccounts.list")
-		mapfile -t etypes < <( sed 's,#.*,, ; s,[[:space:]]*$,, ; /^[[:space:]]*$/d ' "$path/expense_types.list")
-		mapfile -t rtypes < <( sed 's,#.*,, ; s,[[:space:]]*$,, ; /^[[:space:]]*$/d ' "$path/revenue_types.list")
-
-		exec {qiffd}<"$fqif"
 		exec {flowfd}>"$fqif.flow"
-		while read line <&${qiffd} ; do
-			if [[ ${line::1} == "^" ]] ; then
-				((++i))
-				#for k in "${!entry[@]}" ; do
-				#	echo "  $k${entry[$k]}"
-				#done
-				for k in T D P ; do
-					if [[  -z "${entry[$k]}" ]] ; then
-						printf "%s: Error: entry #%s is missing %k field.\n" "$FUNCNAME" "$i" "$k" >&2
-						return 3
-					fi
-				done
-				if [[ ${entry[T]::1} == "-" ]] ; then
-					entry[U]=${entry[T]:1}
-					entry[Mtype]="Debit"
-				else
-					[[ ${entry[T]::1} == "+" ]] && entry[U]=${entry[T]:1} || entry[U]=${entry[T]}
-					entry[Mtype]="Credit"
+		while read line < <(bl_foopgp_qiftobash "$fqif") ; do
+			eval "$line"
+			((++i))
+			#for k in "${!entry[@]}" ; do
+			#	echo "  $k${entry[$k]}"
+			#done
+			for k in T D P ; do
+				if [[  -z "${entry[$k]}" ]] ; then
+					printf "%s: Error: entry #%s is missing %k field.\n" "$FUNCNAME" "$i" "$k" >&2
+					return 3
 				fi
-				entry[D]=$(_bl_foopgp_dateFR2ISO8601 ${entry[D]})
-				entry[Mdesc]="$(echo -e "--- Entry #$i ---\n${entry[D]} - ${entry[Mtype]}: ${entry[U]}\n${entry[P]}\n----------------")"
+			done
+			if [[ ${entry[T]::1} == "-" ]] ; then
+				entry[U]=${entry[T]:1}
+				entry[Mtype]="Debit"
+			else
+				[[ ${entry[T]::1} == "+" ]] && entry[U]=${entry[T]:1} || entry[U]=${entry[T]}
+				entry[Mtype]="Credit"
+			fi
+			entry[D]=$(_bl_foopgp_dateFRtoISO8601 ${entry[D]})
+			entry[Mdesc]="$(echo -e "--- Entry #$i ---\n${entry[D]} - ${entry[Mtype]}: ${entry[U]}\n${entry[P]}\n----------------")"
 
+			while true ; do
+				j=0
+				entry[Msum]=$(($(_bl_foopgp_tonatnum ${entry[T]})))
+				flow=()
 				while true ; do
-					j=0
-					entry[Msum]=$(($(_bl_foopgp_tonatnum ${entry[T]})))
-					flow=()
+					((++j))
+					if ((entry[Msum]<0)) ; then
+						entry[Mdefdir]="Expense"
+					else
+						entry[Mdefdir]="Revenue"
+					fi
+					echo
+					remain=$(_bl_foopgp_todecnum "${entry[Msum]}")
+					direction=$(bl_radiolist --output-value --default-value "${entry[Mdefdir]}" --text "${entry[Mdesc]}"$'\n'$'\n'"  Entry #$i ($remain). Select the nature of subflow #$j" "Revenue" "Expense")
 					while true ; do
-						((++j))
-						if ((entry[Msum]<0)) ; then
-							entry[Mdefdir]="Expense"
-						else
-							entry[Mdefdir]="Revenue"
+						countdec=$(bl_input --default "$(tr -d -- '+-' <<<"$remain" )" --text "  Entry #$i ($remain)." "Enter the amount of subflow #$j ($direction)" | tr -d ' ')
+						if [[ $countdec =~ ^[0-9]+$ ]] ; then
+							countdec+=",00"
 						fi
-						echo
-						remain=$(_bl_foopgp_todecnum "${entry[Msum]}")
-						direction=$(bl_radiolist --output-value --default-value "${entry[Mdefdir]}" --text "${entry[Mdesc]}"$'\n'$'\n'"  Entry #$i ($remain). Select the nature of subflow #$j" "Revenue" "Expense")
-						while true ; do
-							countdec=$(bl_input --default "$(tr -d -- '+-' <<<"$remain" )" --text "  Entry #$i ($remain)." "Enter the amount of subflow #$j ($direction)" | tr -d ' ')
-							if [[ $countdec =~ ^[0-9]+$ ]] ; then
-								countdec+=",00"
-							fi
-							if [[ $countdec =~ ^[0-9]+[.,][0-9][0-9]$ ]] ; then
-								break
-							fi
-						done
-
-						isub1=$(bl_radiolist --output-index --default 1 --text "  Entry #$i. Select the sub-account for subflow #$j" "${subaccounts[@]#*:}")
-						if [[ $direction == "Expense" ]] ; then
-							: $((entry[Msum]+=$(_bl_foopgp_tonatnum "$countdec")))
-							ityp=$(bl_radiolist --output-index --text "  Entry #$i. Select the type of expense for subflow #$j (-$countdec)" "${etypes[@]#*:}")
-							typ=${etypes[$ityp]}
-						else
-							: $((entry[Msum]-=$(_bl_foopgp_tonatnum "$countdec")))
-							ityp=$(bl_radiolist --output-index --default 1 --text "  Entry #$i. Select the type of revenue for subflow #$j (+$countdec)" "${rtypes[@]#*:}")
-							typ=${rtypes[$ityp]}
-						fi
-						if [[ ${typ%%:*} == 1 ]] ; then # 1:Internal
-							local isub2
-							isub2=$(bl_radiolist --output-index --text "  Entry #$i. Select the sub-account for Internal subflow #$j" "${subaccounts[@]#*:}")
-							flow+=("$(printf "${entry[D]} | %-11s | %7s | %-11s | %9s | %38s | $(realpath --relative-to="$path" "$fqif") | #$i | #$j" "${subaccounts[$isub1]}" "$direction" "$typ" "$countdec" "${subaccounts[$isub2]}")")
-							((++j))
-							if [[ $direction == "Expense" ]] ; then
-								direction="Revenue"
-								: $((entry[Msum]-=$(_bl_foopgp_tonatnum "$countdec")))
-							else
-								direction="Expense"
-								: $((entry[Msum]+=$(_bl_foopgp_tonatnum "$countdec")))
-							fi
-							srcdest=${subaccounts[$isub1]}
-							isub1=$isub2
-						elif [[ ${typ%%:*} == 2 ]] ; then # 2:Donation of cash
-							local question dtype
-							[[ $direction == "Expense" ]] && question="To whom was this donation made" || question="In whose name was this donation made"
-							srcdest=$(bl_input --default "${entry[P]}" --email --text "  Entry #$i (${subaccounts[$isub1]#*:}/$direction/${typ#*:}/$countdec)." "$question (email address)")
-						#elif [[ ${typ%%:*} == 3 ]] ; then # 3:Stock Inventory flow will be managed by a futur fonction "flow2stock()"
-						else
-							srcdest=$(bl_input --default "${entry[P]}" --text "  Entry #$i (${subaccounts[$isub1]#*:}/$direction/${typ#*:}/$countdec)." "Enter description, source or destination of subflow #$j")
-						fi
-						flow+=("$(printf "${entry[D]} | %-11s | %7s | %-11s | %9s | %38s | $(realpath --relative-to="$path" "$fqif") | #$i | #$j" "${subaccounts[$isub1]}" "$direction" "$typ" "$countdec" "$srcdest")")
-						if ((entry[Msum]==0)) ; then
-							! bl_yesno --default=yes "Count reached. Next step" || break
+						if [[ $countdec =~ ^[0-9]+[.,][0-9][0-9]$ ]] ; then
+							break
 						fi
 					done
-					if bl_yesno --text "$(printf "%s\n" "${flow[@]}")" --default=yes "Validate entry #$i" ; then
-						printf "%s\n" "${flow[@]}" >&${flowfd}
-						break
+
+					isub1=$(bl_radiolist --output-index --default 1 --text "  Entry #$i. Select the sub-account for subflow #$j" "${subaccounts[@]#*:}")
+					if [[ $direction == "Expense" ]] ; then
+						: $((entry[Msum]+=$(_bl_foopgp_tonatnum "$countdec")))
+						ityp=$(bl_radiolist --output-index --text "  Entry #$i. Select the type of expense for subflow #$j (-$countdec)" "${etypes[@]#*:}")
+						typ=${etypes[$ityp]}
+					else
+						: $((entry[Msum]-=$(_bl_foopgp_tonatnum "$countdec")))
+						ityp=$(bl_radiolist --output-index --default 1 --text "  Entry #$i. Select the type of revenue for subflow #$j (+$countdec)" "${rtypes[@]#*:}")
+						typ=${rtypes[$ityp]}
+					fi
+					if [[ ${typ%%:*} == 1 ]] ; then # 1:Internal
+						local isub2
+						isub2=$(bl_radiolist --output-index --text "  Entry #$i. Select the sub-account for Internal subflow #$j" "${subaccounts[@]#*:}")
+						flow+=("$(printf "${entry[D]} | %-11s | %7s | %-11s | %9s | %38s | $(realpath --relative-to="$path" "$fqif") | #$i | #$j" "${subaccounts[$isub1]}" "$direction" "$typ" "$countdec" "${subaccounts[$isub2]}")")
+						((++j))
+						if [[ $direction == "Expense" ]] ; then
+							direction="Revenue"
+							: $((entry[Msum]-=$(_bl_foopgp_tonatnum "$countdec")))
+						else
+							direction="Expense"
+							: $((entry[Msum]+=$(_bl_foopgp_tonatnum "$countdec")))
+						fi
+						srcdest=${subaccounts[$isub1]}
+						isub1=$isub2
+					elif [[ ${typ%%:*} == 2 ]] ; then # 2:Donation of cash
+						local question dtype
+						[[ $direction == "Expense" ]] && question="To whom was this donation made" || question="In whose name was this donation made"
+						srcdest=$(bl_input --default "${entry[P]}" --email --text "  Entry #$i (${subaccounts[$isub1]#*:}/$direction/${typ#*:}/$countdec)." "$question (email address)")
+					#elif [[ ${typ%%:*} == 3 ]] ; then # 3:Stock Inventory flow will be managed by a futur fonction "flow2stock()"
+					else
+						srcdest=$(bl_input --default "${entry[P]}" --text "  Entry #$i (${subaccounts[$isub1]#*:}/$direction/${typ#*:}/$countdec)." "Enter description, source or destination of subflow #$j")
+					fi
+					flow+=("$(printf "${entry[D]} | %-11s | %7s | %-11s | %9s | %38s | $(realpath --relative-to="$path" "$fqif") | #$i | #$j" "${subaccounts[$isub1]}" "$direction" "$typ" "$countdec" "$srcdest")")
+					if ((entry[Msum]==0)) ; then
+						! bl_yesno --default=yes "Count reached. Next step" || break
 					fi
 				done
-
-				unset entry
-				local -A entry
-			else
-				entry[${line::1}]=${line:1}
-			fi
+				if bl_yesno --text "$(printf "%s\n" "${flow[@]}")" --default=yes "Validate entry #$i" ; then
+					printf "%s\n" "${flow[@]}" >&${flowfd}
+					break
+				fi
+			done
 		done
-		exec {qiffd}<&-
 		exec {flowfd}>&-
 	done
 }
