[bl-foopgp] giftarray() now manage also --tokens and --gifts

diff --git a/bin/bl-foopgp b/bin/bl-foopgp
--- a/bin/bl-foopgp
+++ b/bin/bl-foopgp
@@ -216,19 +216,25 @@ bl_foopgp_giftarray() {
 	local helpmsg="
 Display an array to indicate how many token gonna be created from a gift.
 Options:
-  -c, --currency CODE  Set gift currency (defaut: EUR -> €)
-  -u, --udid UDID      If it is not an initial gift, retrieve total gift and number of token created for a given individual.
+  -t, --tokens DJESUM  Set the base of tokens Ɉ already created (default: 0)
+  -g, --gifts EURSUM   Set the base of values in EUR € already given (default: 0)
   -m, --max VALUE      Set the limit in term of token (defaut: 12)
   -H, --header-only    Only display header line, and return.
   -F, --with-header    Also display header line and separation line at the beginning of array.
 "
 	local max=12 udid header=0 onlyheader=0 ccode=EUR
-	local t g j=1
+	local t g j=1 tg=0 gg=0
 	local -A csymb=([DJE]="Ɉ" [EUR]="€") # cf. ISO-4217 + https://en.wikipedia.org/wiki/Currency_symbol
 	for ((;$#;)) ; do
 		case "$1" in
-			-c|--currency) shift ; printf "%s: Warning: only EUR € is yet implemented" "$FUNCNAME" >&2 ;;
-			-u|--udid) shift ; udid="$1" ; printf "%s: Warning: --udid is not yet implemented" "$FUNCNAME" >&2 ;;
+			-t|--tokens)
+				shift ; tg=${1/,/.}
+				[[ "$tg" =~ ^[0-9]+\.?[0-9]*$ ]] || { printf "%s: Error: given parameter '%s' is not a valid number.\n" "$FUNCNAME" "$tg" >&2 ; return 2 ; }
+				;;
+			-g|--gifts)
+				shift ; gg=${1/,/.}
+				[[ "$gg" =~ ^[0-9]+\.?[0-9]*$ ]] || { printf "%s: Error: given parameter '%s' is not a valid number.\n" "$FUNCNAME" "$gg" >&2 ; return 2 ; }
+				;;
 			-m|--max) shift ; max=$(($1)) ;;
 			-H|--header-only) onlyheader=1 header=1 ;;
 			-F|--with-header) onlyheader=0 header=1 ;;
@@ -245,9 +251,9 @@ Options:
 	((!header)) || echo "|--------------|-------------|"
 	j=1
 	for ((i=1;i<=$max;i++)) ; do
-		g=$(bl_foopgp_t2g $i)
+		g=$(bl_foopgp_t2g --tokens "$tg" --gifts "$gg" $i)
 		while (( $(echo "$j < $g" | bc -l) )) ; do
-			LC_NUMERIC=POSIX printf "| %7s.00 ${csymb[EUR]} | %9s Ɉ |\n" "$j" "$(bl_foopgp_g2t $j)"
+			LC_NUMERIC=POSIX printf "| %7s.00 ${csymb[EUR]} | %9s Ɉ |\n" "$j" "$(bl_foopgp_g2t --tokens "$tg" --gifts "$gg" $j)"
 			((j*=2))
 			j=$(tr '4' '5' <<<"$j")
 		done
