start internationalisation and localisation

diff --git a/bin/bl-json b/bin/bl-json
--- a/bin/bl-json
+++ b/bin/bl-json
@@ -67,6 +67,11 @@ readonly BL_JSON_NAME BL_JSON_VERSION BL_JSON_FUNCTIONS
 
 ### Default option values ###
 
+TEXTDOMAIN="${TEXTDOMAIN:-bashlibs}"
+TEXTDOMAINDIR="${TEXTDOMAINDIR:-$(dirname "$(readlink -f "$BASH_SOURCE")" )/../share/locale}"
+# Require Bash 5.2. - https://www.kurokatta.org/grumble/2023/11/bash-translated-strings#fnref3
+shopt -s noexpand_translation
+
 ### external functions ###
 
 ### internal functions ###
@@ -272,7 +277,7 @@ Examples:
 			if [[ "$varname" ]] ; then
 				printf "declare -- $varname=''\n"
 			else
-				printf $"%s: Info: JSON 'null' -> BASH ''.\n" "$FUNCNAME" >&2
+				printf "%s: Info: JSON 'null' -> BASH ''.\n" "$FUNCNAME" >&2
 			fi
 			return
 			;;
@@ -284,7 +289,7 @@ Examples:
 
 		array) [[ -z "$varname" ]] || echo "declare -a -- $varname=(" ;;
 		object) [[ -z "$varname" ]] || echo "declare -A -- $varname=(" ;;
-		*) printf $"%s: Error: Invalid JSON (%s).\n" "$FUNCNAME" "${lines[0]:: 8}..." >&2
+		*) echo "$FUNCNAME: Error:" $"Invalid JSON" "(${lines[0]:: 8}...)." >&2
 		   return 2 ;;
 	esac
 
@@ -308,9 +313,9 @@ Examples:
 				# escape all double quotes, then double quote all.
 				echo "$value" | sed "$sed4jvalue"'s,",\\",g ; 1s,^,", ; $s,$,", ; ' ;;
 			*)
-			   echo
-			   printf $"%s: Error: Invalid JSON (%s).\n" "$FUNCNAME" "${value:: 8}..." >&2
-			   return 2 ;;
+				echo
+				echo "$FUNCNAME: Error:" $"Invalid JSON" "(${lines[0]:: 8}...)." >&2
+				return 2 ;;
 		esac
 	done
 
diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -327,6 +327,11 @@ BL_PGPID_KEYSERVERS=(
 "hkps://keys.foopgp.org"
 )
 
+TEXTDOMAIN="${TEXTDOMAIN:-bashlibs}"
+TEXTDOMAINDIR="${TEXTDOMAINDIR:-$(dirname "$(readlink -f "$BASH_SOURCE")" )/../share/locale}"
+# Require Bash 5.2. - https://www.kurokatta.org/grumble/2023/11/bash-translated-strings#fnref3
+shopt -s noexpand_translation
+
 ### external functions ###
 
 source "$(dirname "$BASH_SOURCE")"/bl-interactive --
@@ -575,7 +580,7 @@ People have to check, and fix when NOK.
 			-h|--h*) echo "$helpmsg" ; return ;;
 			-V|--version) printf "%s %s\n" "$FUNCNAME" "$BL_PGPID_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) echo -e "$name: Error: Unrecognized option/parameters $1\n$helpmsg" >&2 ; return 2 ;;
+			-*) echo -e "$name: Error:" $"Unrecognized option/parameters"" $1\n$helpmsg" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
@@ -583,14 +588,14 @@ People have to check, and fix when NOK.
 
 	local -A mrza
 	if ! _bl_icao9303_mrz_analyse $uncheck mrza "$@" ; then
-		printf "%s: %s: Invalid Machine Readable Zone (ICAO9303)\n" "Error" "$FUNCNAME" >&2
+		echo "$FUNCNAME: Error:" $"Invalid Machine Readable Zone (ICAO9303)" >&2
 		return 1
 	fi
 
 	local allnames bdate countrycode coordinates
 
 	if ! allnames=$(LC_COLLATE="C.UTF-8" grep -o "[A-Z]\{1,32\}<<[A-Z]\{1,32\}<[A-Z]\{0,32\}<" <<<"${mrza[all_names]}" ) ; then
-		printf "%s: Error: no valid and complete surname and given names extracted from '%s'\n" "$FUNCNAME" "${mrza[all_names]}" >&2
+		echo "$FUNCNAME: Error:" $"No valid and complete surname and given names extracted from" "${mrza[all_names]}" >&2
 		return 1
 	fi
 
@@ -689,7 +694,7 @@ Options:
 	sname=$(sed 's,[ ;,<-]\+,<,g'<<<"$sname" ) # replace and squeeze some word separators
 	translit=$(iconv -f utf-8 -t ascii//TRANSLIT <<<"$sname") # transliterate (according to iconv), may differ from Passport transliterations.
 	if [[ "$translit" != "$sname" ]] ; then
-		printf "%s: Warning: '%s' has been transliterated to '%s'. It may be WRONG !\n" "$FUNCNAME" "$sname" "$translit" >&2
+		echo "$FUNCNAME: Warning: '$sname'" $"has been transliterated to" "'$translit'." $"It may be WRONG !" >&2
 		sname="$translit"
 	fi
 	sname="${sname^^}" # uppercase
@@ -908,20 +913,20 @@ bl_pgpid_avatar() {
 	local tmpdir="/tmp/$FUNCNAME.$USER"
 	local usage="Usage: $name [OPTIONS]... [NAME|KEYID|U4|U5]"
 	local keyserv #=${BL_PGPID_KEYSERVERS[0]}
-	local helpmsg="
-Extract and/or add image from/to OpenPGP certificate.
-Missing NAME|KEYID|U4|U5 => KEYID of secret key may be asked interactively.
-New IMAGE should be 180 pixel height, or it will be resized.
-Ouput extracted *.jpg files inside working directory.
+	local helpmsg='
+'$"Extract or add image inside OpenPGP certificate."'
+'$"Missing NAME|KEYID|U4|U5 => KEYID of secret key may be asked interactively."'
+'$"New IMAGE should be 180 pixel height, or it will be resized."'
+'$"Ouput extracted *.jpg files inside working directory."'
 
-Options:
-  -E, --extract-all           Extract also all revoked or expired existing images from OpenPGP certificate.
-  -A, --addfrom IMAGE         Resize and add new IMAGE inside OpenPGP certificate (revoking any previous image).
-  -R, --revoke                Just revoke all existing images inside OpenPGP certificate.
-  -W, --workdir DIRECTORY     Working directory. Will contain previous and new resized images (default: $tmpdir).
-  -k, --keyserver KEYSERVER   If non-empty, send updated certificate to this keyserver (default: $keyserv).
-  -H, --homedir GNUPGHOME     GnuPG home directory (default: ~/.gnupg). Environnement variable: \$GNUPGHOME.
-"
+'$"Options:"'
+  -E, --extract-all           '$"Extract also all revoked or expired existing images from OpenPGP certificate."'
+  -A, --addfrom IMAGE         '$"Resize and add new IMAGE inside OpenPGP certificate (revoking any previous image)."'
+  -R, --revoke                '$"Just revoke all existing images inside OpenPGP certificate."'
+  -W, --workdir DIRECTORY     '$"Working directory. Will contain previous and new resized images (default:"" $tmpdir)."'
+  -k, --keyserver KEYSERVER   '$"If non-empty, send updated certificate to this keyserver (default:"" $keyserv)."'
+  -H, --homedir GNUPGHOME     '$"GnuPG home directory (default: ~/.gnupg). Environnement variable:"' $GNUPGHOME.
+'
 	local image revoke
 	local gpghome=${GNUPGHOME:-~/.gnupg}
 	local listopts="show-photos"
@@ -1086,7 +1091,7 @@ Options:
 
 		ids=($(sed --silent --regexp-extended "s,.*4.?(${BL_PGPID_U4_REGEX}).*,u4=\1,p ; s,.*5.?(${BL_PGPID_U5_REGEX}).*,u5=\1,p" <<<"$uids" | sort -u))
 		(( ${#ids[@]} > 0 )) || { printf "%s: Error: No pgpid string (u4|u5) in %s certificate\n" "$FUNCNAME" "$user" >&2 ; return 1 ;}
-		(( ${#ids[@]} < 2 )) || { printf "%s: Error: supernumerary %s (%s)\n" "$FUNCNAME" "id" "${ids[*]}" >&2 ; return 1 ;}
+		(( ${#ids[@]} < 2 )) || { echo "$FUNCNAME: Error:" $"supernumerary pgpid string" "(${ids[*]})" >&2 ; return 1 ;}
 
 		# Add emails
 		for email in "${toadd[@]}" ; do
@@ -1212,11 +1217,11 @@ Options:
 	done <<<"${cardstatus}"
 
 	aaname[pgpid_email]="${emails[0]}"
-	(( $(sort -u <<<"${emails[@]}" | wc -l) < 2 )) || ((quiet)) || printf "%s: Notice: supernumerary %s, skipping %s ...\n" "$FUNCNAME" "email" "$(sort -u <<<"${emails[@]}" | grep -v "${emails[0]}")" >&2
+	(( $(sort -u <<<"${emails[@]}" | wc -l) < 2 )) || ((quiet)) || echo "$FUNCNAME: Notice:" $"supernumerary emails, skipping" "$(sort -u <<<"${emails[@]}" | grep -v "${emails[0]}") ..." >&2
 
 	# Should be in 'Login data' field, but who knows ? (yet...) 
 	ids=($(sed --silent --regexp-extended "s,.*4.?(${BL_PGPID_U4_REGEX}).*,u4\1,p ; s,.*5.?(${BL_PGPID_U5_REGEX}).*,u5\1,p" <<<"${cardstatus}" | sort -u))
-	(( ${#ids[@]} < 2 )) || { printf "%s: Error: supernumerary %s (%s)\n" "$FUNCNAME" "id" "${ids[*]}" >&2 ; return 1 ;}
+	(( ${#ids[@]} < 2 )) || { echo "$FUNCNAME: Error:" $"supernumerary pgpid string" "(${ids[*]})" >&2 ; return 1 ;}
 	aaname[pgpid_id]="${ids[0]}"
 
 	aaname[token_AVersion]="${ttype} ${tversion}"
diff --git a/bin/bl-qrkey b/bin/bl-qrkey
--- a/bin/bl-qrkey
+++ b/bin/bl-qrkey
@@ -81,6 +81,11 @@ readonly BL_QRKEY_NAME BL_QRKEY_VERSION BL_QRKEY_FUNCTIONS
 
 ### Default option values ###
 
+TEXTDOMAIN="${TEXTDOMAIN:-bashlibs}"
+TEXTDOMAINDIR="${TEXTDOMAINDIR:-$(dirname "$(readlink -f "$BASH_SOURCE")" )/../share/locale}"
+# Require Bash 5.2. - https://www.kurokatta.org/grumble/2023/11/bash-translated-strings#fnref3
+shopt -s noexpand_translation
+
 ### external functions ###
 
 source "$(dirname "$BASH_SOURCE")"/bl-interactive --
@@ -791,7 +796,7 @@ Options:
 			-K|--pubkey)
 				shift ; pubkeyfile="$1" ;;
 			-v|--verbose) gpgfilter="cat" ;;
-			--no-send) echo "$FUNCNAME:" $"Warning:" $"Deprecated option" "$1" >&2 ;;
+			--no-send) echo "$FUNCNAME: Warning:" $"Deprecated option" "$1" >&2 ;;
 			--force) force=1 ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
 			-V|--version) printf "%s %s\n" "$FUNCNAME" "$BL_QRKEY_VERSION" ; return ;;
@@ -830,14 +835,14 @@ Options:
 
 	# Don't error if there is no pgp_id
 	ids=($(sed --silent --regexp-extended "s,.*4.?(${BL_PGPID_U4_REGEX}).*,u4\1,p ; s,.*5.?(${BL_PGPID_U5_REGEX}).*,u5\1,p" <<<"${secstatus}" | sort -u))
-	(( ${#ids[@]} < 2 )) || { printf "%s: Error: supernumerary %s (%s)\n" "$FUNCNAME" "id" "${ids[*]}" >&2 ; return 1 ;}
+	(( ${#ids[@]} < 2 )) || { echo "$FUNCNAME: Error:" $"supernumerary pgpid string" "(${ids[*]})" >&2 ; return 1 ;}
 
 	# Check and errout card-status
 	bl_pgpid_token_check --homedir "$gpghome" --no-fetch --quiet --aaname tcheck_info || tcheck_rvalue=$?
 
 	[[ "${tcheck_info[token_MSN]}" ]] || return $tcheck_rvalue
 
-	echo "$FUNCNAME:" $"Notice:" $"Detected OpenPGP security token:" "${tcheck_info[token_MSN]} -" $"Cardholder:" "${tcheck_info[pgpid_name]} <${tcheck_info[pgpid_email]}>" >&2
+	echo "$FUNCNAME: Notice:" $"Detected OpenPGP security token:" "${tcheck_info[token_MSN]} -" $"Cardholder:" "${tcheck_info[pgpid_name]} <${tcheck_info[pgpid_email]}>" >&2
 
 	# If we fail testing no passphrase, there is one. Then we have to remove it, or we can't exec gpg's keytocard
 	if ! gpg --homedir "$gpghome" --batch --pinentry-mode loopback --passphrase "" --dry-run --change-passphrase "$keyid" 2> /dev/null ; then
@@ -850,7 +855,7 @@ Options:
 	fi
 
 	((tcheck_rvalue==107)) || ((force)) || bl_yesno --text "${tcheck_info[token_MSN]} " \
-		$"Factory reset OpenPGP security token" $"(This will destroys all OpenPGP keys stored on the card!)" || exit 42
+		$"Factory reset OpenPGP security token" $"(This will wipe all the OpenPGP data stored there!)" || exit 42
 
 	printf "%s: Notice: Resetting OpenPGP security token...\n" "$FUNCNAME" >&2
 
