bl_json_to_var(): bug fixes

diff --git a/bin/bl-json b/bin/bl-json
--- a/bin/bl-json
+++ b/bin/bl-json
@@ -269,25 +269,49 @@ Examples:
 	jsontype="$(bl_json_type "${lines[0]}")"
 	case "$jsontype" in
 		null)
-			[[ "$varname" ]] || echo "null"
-			# TODO Maybe: add an warning message to explain this case.
+			if [[ "$varname" ]] ; then
+				printf "declare -- $varname=''\n"
+			else
+				printf $"%s: Info: JSON 'null' -> BASH ''.\n" "$FUNCNAME" >&2
+			fi
 			return
 			;;
 		boolean|string|number)
-			[[ "$varname" ]] && printf "declare -- $varname="
+			[[ -z "$varname" ]] || printf "declare -- $varname="
 			echo "${lines[0]%,}" # remove eventual trailing comma
 			return
 			;;
 
-		array) [[ "$varname" ]] && echo "declare -a $varname=(" ;;
-		object) [[ "$varname" ]] && echo "declare -A $varname=(" ;;
-		*) echo "$FUNCNAME: Error: Invalid JSON." >&2
+		array) [[ -z "$varname" ]] || echo "declare -a -- $varname=(" ;;
+		object) [[ -z "$varname" ]] || echo "declare -A -- $varname=(" ;;
+		*) printf $"%s: Error: Invalid JSON (%s).\n" "$FUNCNAME" "${lines[0]:: 8}..." >&2
 		   return 2 ;;
 	esac
 
-	for key in $(echo "${lines[@]}" | jq '. | keys' | sed 's,^.,, ; s/,$// ' ) ; do
-		echo "[$key]=\"$(jq --compact-output --join-output ".[$key]" <<<"${lines[@]}" | sed 's,",\\",g' )\""
-		#echo "[$key]=$(jq ".[$key]" <<<"${lines[@]}" | bl_json_to_var)"
+	local keys key jkey value
+
+	local sed4eval='s,\\,\\\\,g ; s,\$,\\$,g ; '
+	local sed4jvalue
+	[[ -z "$varname" ]] || sed4jvalue="$sed4eval"
+
+	eval keys=($(echo "${lines[@]}" | jq '. | keys' | sed 's,^.,, ; s/,$// ; '"$sed4eval" ))
+	for key in "${keys[@]}" ; do
+		[[ "$jsontype" == array ]] && jkey=$key || jkey="\"$key\""
+		value=$(jq ".[$jkey]" <<<"${lines[@]}")
+		printf "[${key@Q}]="
+		case "$(bl_json_type "${value}")" in
+			null)
+				echo '""' ;;
+			boolean|string|number)
+				echo "$value" | sed "$sed4jvalue" ;;
+			array|object)
+				# escape all double quotes, then double quote all.
+				echo "$value" | sed "$sed4jvalue"'s,",\\",g ; 1s,^,", ; $s,$,", ; ' ;;
+			*)
+			   echo
+			   printf $"%s: Error: Invalid JSON (%s).\n" "$FUNCNAME" "${value:: 8}..." >&2
+			   return 2 ;;
+		esac
 	done
 
 	[[ "$varname" ]] && echo ")"
