bl-pgpid: fix bugs and manage a little transliteration

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -65,7 +65,8 @@ declare -r BL_PGPID_VERSION="0.0.4"
 declare -r BL_PGPID_FUNCTIONS=( $(sed -n 's,^\(bl_[^( ]*\) *().*,\1,p' "$BASH_SOURCE") )
 
 declare -r BL_PGPID_CO_REGEX="e[_-][0-9]{2}\.[0-9]{2}[_-][01][0-9]{2}\.[0-9]{2}"
-declare -r BL_PGPID_U4H_REGEX="[a-zA-Z0-9_-]{22}"
+# Best way to NOT manage LC_COLLATE(="C.UTF-8") - cf. https://unix.stackexchange.com/questions/645054/how-do-bash-and-zsh-handle-collation-in-patterns-and-regexes
+declare -r BL_PGPID_U4H_REGEX="[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0-9_-]{22}"
 declare -r BL_PGPID_U4_REGEX="${BL_PGPID_U4H_REGEX}${BL_PGPID_CO_REGEX}"
 declare -r BL_PGPID_N2_REGEX="(18|19|20)[0-9]{2}(0[1-9]|1[0,1,2])(0[1-9]|[12][0-9]|3[01])${BL_PGPID_CO_REGEX}"
 
@@ -454,7 +455,7 @@ People have to check, and fix when NOK.
 			-d|--birth-d*) shift ; gdate=$(sed ' s,[^0-9],,g ' <<<"$1") ;; # keep only [0-9] from given input
 			-u|--uncheck) uncheck="--uncheck" ;;
 			-h|--h*) echo "$helpmsg" ; return ;;
-			-V|--version) printf "%s %s\n" "$name" "$BL_PGPID_VERSION" ; return ;;
+			-V|--version) printf "%s %s\n" "$FUNCNAME" "$BL_PGPID_VERSION" ; return ;;
 			--) shift ; break ;;
 			-*) echo -e "$name: Error: Unrecognized option/parameters $1\n$helpmsg" >&2 ; return 2 ;;
 			*) break ;;
@@ -466,29 +467,29 @@ People have to check, and fix when NOK.
 	local allnames bdate countrycode coordinates
 
 	if ! _bl_icao9303_mrz_analyse $uncheck mrza "$@" ; then
-		printf "%s: Error: Can't analyse given Machine Readable Zone (ICAO9303)\n" "$name" >&2
+		printf "%s: Error: Can't analyse given Machine Readable Zone (ICAO9303)\n" "$FUNCNAME" >&2
 			return 1
 	fi
 
-	if ! allnames=$(grep -o "[A-Z]\{1,32\}<<[A-Z]\{1,32\}<[A-Z]\{0,32\}<" <<<"${mrza[all_names]}" ) ; then
-		printf "%s: Error: no complete surname and given names extracted from '%s'\n" "$name" "${mrza[all_names]}" >&2
+	if ! allnames=$(LC_COLLATE="C.UTF-8" grep -o "[A-Z]\{1,32\}<<[A-Z]\{1,32\}<[A-Z]\{0,32\}<" <<<"${mrza[all_names]}" ) ; then
+		printf "%s: Error: no valid and complete surname and given names extracted from '%s'\n" "$FUNCNAME" "${mrza[all_names]}" >&2
 		return 1
 	fi
 
 	countrycode="${mrza[country]}"
 	coordinates="${BL_PGPID_COORDINATES[$countrycode]: 0:14}"
 	if ! [[ "$coordinates" =~ ^${BL_PGPID_CO_REGEX}$ ]] ; then
-		printf "%s: Error: Invalid coordinates (%s) for country '%s'\n" "$name" "$coordinates" "$countrycode" >&2
+		printf "%s: Error: Invalid coordinates (%s) for country '%s'\n" "$FUNCNAME" "$coordinates" "$countrycode" >&2
 		return 1
 	fi
 
 	if [[ "$gdate" ]] ; then
-		((${#gdate}==8)) || printf "%s: Notice: Invalid lenght for birth date '%s'\n" "$name" "$gdate" >&2
+		((${#gdate}==8)) || printf "%s: Notice: Invalid lenght for birth date '%s'\n" "$FUNCNAME" "$gdate" >&2
 	else
 		gdate="${mrza[date_of_birth]}"
 	fi
 	if ! bdate=$(date --date "${gdate}" +"%Y-%m-%d" ) ; then
-		printf "%s: Error: Can't reformart birthdate '%s'\n" "$name" "$gdate" >&2
+		printf "%s: Error: Can't reformart birthdate '%s'\n" "$FUNCNAME" "$gdate" >&2
 		return 1
 	fi
 
@@ -510,7 +511,7 @@ Options:
   -c, --birth-country COUNTRY_CODE 3 letters country code of birth place: FRA, GBR, ...
   -v, --verify                     Ask for verification
 "
-	local sname gname bdate bcountry verify=""
+	local sname gname translit bdate bcountry verify=""
 	for ((;$#;)) ; do
 		case "$1" in
 			-s|--s*)
@@ -523,9 +524,9 @@ Options:
 				shift ; bcountry=$1 ;;
 			-v|--verify) verify=1 ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
-			-V|--version) printf "%s %s\n" "$name" "$BL_PGPID_VERSION" ; return ;;
+			-V|--version) printf "%s %s\n" "$FUNCNAME" "$BL_PGPID_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$name" "$1" "$name" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
@@ -535,7 +536,7 @@ Options:
 	if [[ "$1" ]] ; then
 		local -A mrza=()
 		if ! _bl_icao9303_mrz_analyse mrza "$@" ; then
-			printf "%s: Warning: Can't analyse given Machine Readable Zone (ICAO9303)\n" "$name" >&2
+			printf "%s: Warning: Can't analyse given Machine Readable Zone (ICAO9303)\n" "$FUNCNAME" >&2
 		else
 			[[ "$sname" ]] || sname=$(tr '<' ' ' <<<"${mrza[all_names]%%<<*}")
 			[[ "$gname" ]] || gname=$(sed ' s,<*$,,g ; s,<, , ' <<<"${mrza[all_names]#*<<}")
@@ -545,11 +546,8 @@ Options:
 	fi
 
 	[[ "$sname" ]] || sname=$(bl_input "Birth surname (family name)")
-
-	[[ "$gname" ]] || gname=$(bl_input --default "${gname}" "Birth names (given names)")
-
-	[[ "$bdate" ]] || bdate=$(bl_input --default "${bdate}" "Birth date (YYYY-MM-DD)")
-
+	[[ "$gname" ]] || gname=$(bl_input "Birth names (given names)")
+	[[ "$bdate" ]] || bdate=$(bl_input "Birth date (YYYY-MM-DD)")
 	[[ "$bcountry" ]] || bcountry=$(bl_input --default "FRA" "Birth country (3 letter code)")
 
 	while [[ "$verify" ]] ; do
@@ -569,12 +567,23 @@ Options:
 	done
 
 	sname=$(sed 's,[ ;,<-]\+,<,g'<<<"$sname" ) # replace and squeeze some word separators
+	translit=$(iconv -f utf-8 -t ascii//TRANSLIT <<<"$sname") # transliterate (according to iconv), may differ from Passport transliterations.
+	if [[ "$translit" != "$sname" ]] ; then
+		printf "%s: Warning: '%s' has been transliterated to '%s'. It may be WRONG !\n" "$FUNCNAME" "$sname" "$translit" >&2
+		sname="$translit"
+	fi
 	sname="${sname^^}" # uppercase
+
 	gname=$(sed 's,[ ;,<-]\+,<,g'<<<"$gname" )
+	translit=$(iconv -f utf-8 -t ascii//TRANSLIT <<<"$gname")
+	if [[ "$translit" != "$gname" ]] ; then
+		printf "%s: Warning: '%s' has been transliterated to '%s'. It may be WRONG !\n" "$FUNCNAME" "$gname" "$translit" >&2
+		gname="$translit"
+	fi
 	gname="${gname^^}"
 
-	if ! fakemrz="P<${bcountry}$(grep -o "[A-Z]\{1,32\}<<[A-Z]\{1,32\}<[A-Z]\{0,32\}<" <<<"${sname}<<$gname<<" )" ; then
-		printf "%s: Error: only [A-Z] characters allowed in names.\n" "$name" >&2
+	if ! fakemrz="P<${bcountry}$(LC_COLLATE="C.UTF-8" grep -o "[A-Z]\{1,32\}<<[A-Z]\{1,32\}<[A-Z]\{0,32\}<" <<<"${sname}<<$gname<<" )" ; then
+		printf "%s: Error: only [A-Z] characters allowed in names.\n" "$FUNCNAME" >&2
 		return 1
 	fi
 	fakemrz+="<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
@@ -609,9 +618,9 @@ Options:
 			-g|--ignore-garbage)
 				iextraopts+="--ignore-garbage " ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
-			-V|--version) printf "%s %s\n" "$name" "$BL_PGPID_VERSION" ; return ;;
+			-V|--version) printf "%s %s\n" "$FUNCNAME" "$BL_PGPID_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$name" "$1" "$name" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
@@ -631,7 +640,7 @@ Options:
 		base64|base64url|base32|base32hex|base16|base2msbf|base2lsbf)
 			decoder="basenc --decode --$ienc $iextraopts" ;;
 		*)
-			printf "%s: Error: unrecognized encoding '%s'\nTry '%s --help' for more information.\n" "$name" "$ienc" "$name" >&2 ; return 2 ;;
+			printf "%s: Error: unrecognized encoding '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$ienc" "$name" >&2 ; return 2 ;;
 	esac
 
 	while read offset hex char; do
@@ -657,7 +666,7 @@ Options:
 		base64|base64url|base32|base32hex|base2msbf|base2lsbf)
 			echo "$hex" | xxd -r -p | basenc --$oenc ;;
 		*)
-			printf "%s: Error: unrecognized encoding '%s'\nTry '%s --help' for more information.\n" "$name" "$ienc" "$name" >&2 ; return 2 ;;
+			printf "%s: Error: unrecognized encoding '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$ienc" "$name" >&2 ; return 2 ;;
 	esac
 }
 
@@ -702,9 +711,9 @@ Options:
 		case "$1" in
 			-f|--free-input) freeinput=1 ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
-			-V|--version) printf "%s %s\n" "$name" "$BL_PGPID_VERSION" ; return ;;
+			-V|--version) printf "%s %s\n" "$FUNCNAME" "$BL_PGPID_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$name" "$1" "$name" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
@@ -724,7 +733,7 @@ Options:
 	elif [[ "$str_in" =~ ${BL_PGPID_U4H_REGEX} ]] ; then
 		u4h="${BASH_REMATCH[0]}=="
 	else
-		printf "%s: Error: No udid4 (hash) found in '%s'...\n" "$name" "${str_in: 0:44}" >&2
+		printf "%s: Error: No udid4 (hash) found in '%s'...\n" "$FUNCNAME" "${str_in: 0:44}" >&2
 		return 2
 	fi
 
@@ -770,9 +779,9 @@ Options:
 				shift ; gpghome=$1 ;;
 			-v|--verify) verify=1 ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
-			-V|--version) printf "%s %s\n" "$name" "$BL_PGPID_VERSION" ; return ;;
+			-V|--version) printf "%s %s\n" "$FUNCNAME" "$BL_PGPID_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$name" "$1" "$name" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
@@ -797,7 +806,7 @@ Options:
 	elif [[ -z "$comment" ]] ; then
 		comment="generated with $name"
 	else
-		printf "%s: Notice: unexpected comment: %s\n" "$name" "$comment" >&2
+		printf "%s: Notice: unexpected comment: %s\n" "$FUNCNAME" "$comment" >&2
 	fi
 
 	local genkey_batch="
