bl-pgpid: new function bl_pgpid_gen_key()

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -435,7 +435,7 @@ Convert the Machine Readable Zone of an icao9303 passport to an udid4 (aka 'u4')
 
 Option:
   -u, --uncheck                Dont verify checksums
-  -d, --birth-date BIRTH_DATE  Birth date, expected format : YYYY-MM-DD (for people born 100+ years ago)
+  -d, --birth-date YYYY-MM-DD  Birth date, expected format : Year-Month-Day (for people born 100+ years ago)
 
 WARNING: mrz data may be irrelevant to generate udid4. eg:
          * Surname or given names may be incomplete (cut bc exceed mrz size)
@@ -501,10 +501,11 @@ bl_pgpid_gen_u4() {
 	local helpmsg="
 Generate udid4. Missing input is asked interactively.
 You may pass the Machine Readable Zone of an international passport as argument, but there are ~20% chances that generated udid4 is incorrect.
+
 Options:
   -s, --surname SURNAME            Surname/family name at birth
   -g, --given-names GIVEN_NAMES    Given names at birth, separated by space ' ' or comma ',' or hyphen '-'.
-  -d, --birth-date BIRTH_DATE      Birth date, expected format : YYYY-MM-DD.
+  -d, --birth-date YYYY-MM-DD      Birth date, expected format : Year-Month-Day.
   -c, --birth-country COUNTRY_CODE 3 letters country code of birth place: FRA, GBR, ...
   -v, --verify                     Ask for verification
 "
@@ -679,6 +680,8 @@ bl_pgpid_gen_uid() {
 #   If we let 4294967294, 4294967293 and id under 2^18 (< 262144), for some futur usage/convention,
 #   then we can use range 262144 to 4294967292, to get an almost unique Unix User ID from unique foopgp User ID (udid4,...)
 #
+#   Confer https://www.debian.org/doc/debian-policy/ch-opersys.html#users-and-groups
+#
 #   Which make 4294705148 slots, ~= about half of the actual human population (~8 billions).
 #   Constants: BL_PGPID_XUID_MIN and BL_PGPID_XUID_MAX
 
@@ -726,6 +729,98 @@ Options:
 
 	num=$(bl_pgpid_2num --input-encoding base64url $((BL_PGPID_XUID_MAX - BL_PGPID_XUID_MIN)) <<<"$u4h") && echo $((num + BL_PGPID_XUID_MIN))
 }
+
+bl_pgpid_gen_key() {
+	local name
+	((BL_PGPID_isprogram)) && name="$BL_PGPID_NAME ${FUNCNAME:9}" || name="$FUNCNAME"
+	local usage="Usage: $name [OPTIONS]... EMAIL"
+	local passphrase=$(date -I)
+	local helpmsg="
+Generate an OpenPGP key pair (public and secret) according to foopgp standards.
+Output 3 lines for each fingerprints :
+* main key (Sign Certify)
+* decryption key (Encrypt)
+* authentication key (Auth)
+
+Options:
+  -n, --name PSEUDONYM             Common name or pseudonym (default: first part of email)
+  -c, --comment UDID4              Comment field, expect an udid4, regex: ${BL_PGPID_U4_REGEX}
+  -p, --passphrase PASSPHRASE      Passphrase to (symetric) encrypt secret part of OpenPGP key (default: ${passphrase})
+  -e, --expiration YEARS           Number of years befor of certificate expiration (default: 11 -> $(date -I -d "+11 years"))
+  -k, --keyserver KEYSERVER        Prefered OpenPGP certificate server (default: hkp://keys.foopgp.org)
+  -H, --homedir GNUPGHOME          GnuPG home directory (default: ~/.gnupg). Environnement variable: \$GNUPGHOME
+"
+	local email pseudo comment keyserv="hkp://keys.foopgp.org" gpghome
+	local gpghome=${GNUPGHOME:-~/.gnupg}
+	local expire=11 verify=""
+	for ((;$#;)) ; do
+		case "$1" in
+			-n|--name*)
+				shift ; pseudo=$1 ;;
+			-c|--comment)
+				shift ; comment=$1 ;;
+			-p|--passphrase)
+				shift ; passphrase=$1 ;;
+			-e|--expir*)
+				shift ; expire=$1 ;;
+			-k|--keyserver)
+				shift ; keyserv=$1 ;;
+			-H|--homedir)
+				shift ; gpghome=$1 ;;
+			-v|--verify) verify=1 ;;
+			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
+			-V|--version) printf "%s %s\n" "$name" "$BL_PGPID_VERSION" ; return ;;
+			--) shift ; break ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$name" "$1" "$name" >&2 ; return 2 ;;
+			*) break ;;
+		esac
+		shift
+	done
+
+	if ! [[ "$1" =~ ^${BL_INTERACTIVE_EMAIL_REGEX}$ ]] ; then
+		printf "$usage\n" >&2
+		return 2
+	fi
+	email="$1"
+	shift
+
+#TODO: implement --verify to check input and ask when incoherent or missing.
+#TODO (also): check gpg version, because we use some recent feature, and compatibility may change (tested with gpg (GnuPG) 2.2.27 libgcrypt 1.8.8)
+
+	[[ "$pseudo" ]] || pseudo=${email%%@*}
+	[[ "$comment" ]] || comment="generated with $name"
+
+	local genkey_batch="
+%echo Generating OpenPGP key for ${email}
+Key-Type: eddsa
+Key-Curve: Ed25519
+Key-Usage: cert sign
+Subkey-Type: ecdh
+Subkey-Curve: Curve25519
+Subkey-Usage: encrypt
+Name-Real: ${pseudo}
+Name-Comment: ${comment}
+Name-Email: ${email}
+Expire-Date: $(date -I -d "+$expire years")
+Passphrase: ${passphrase}
+Keyserver: ${keyserv}
+# Do a commit here, so that we can later print 'done' :-)
+%commit
+"
+
+	gpg --homedir "$gpghome" --batch --generate-key --allow-freeform-uid <<<"$genkey_batch" || return $?
+
+	# get first 2 fprs
+	local fprs
+	fprs=($(gpg --homedir "$gpghome" --list-secret-keys --with-colons "$email" | sed -n 's,^fpr:.*:\([[:xdigit:]]\{40\}\):,\1,p')) || return $?
+
+	# Generate and add auth key...
+	gpg --homedir "$gpghome" --batch --passphrase "${passphrase}" --pinentry-mode loopback --quick-add-key ${fprs[0]} ed25519 auth ${expire}y || return $?
+
+	# output all (3) fingerprints, first fingerprint should be the one of the main key
+	gpg --homedir "$gpghome" --list-secret-keys --with-colons "$email" | sed -n 's,^fpr:.*:\([[:xdigit:]]\{40\}\):,\1,p'
+}
+
 
 ### General Help Messages (and set -e if program) ###
 
