1 bugfix in bl_pgpid_certify() + many typofix in bl-pgpid

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -997,7 +997,7 @@ OPTIONS:
 	fi
 
 	if [[ "$revoke" ]] ; then
-		(( ${#fprs[@]} < 2 )) || { printf "$FUNCNAME: Error: "$"User '%s' match many certificates (%s)"".\n" "$user" "${fprs[*]}" >&2 ; return 1 ;}
+		(( ${#fprs[@]} < 2 )) || { printf "$FUNCNAME: Error: "$"User '%s' match many (%d) certificates"" (%s).\n" "$user" ${#fprs[@]} "${fprs[*]}" >&2 ; return 1 ;}
 
 		local commands
 		# Revoke non-revoked photos (in first keyring only))
@@ -1089,7 +1089,7 @@ OPTIONS:
 	local fprs
 	fprs=($(gpg --homedir "$gpghome" --list-options show-only-fpr-mbox --list-key "$user" | cut -d ' ' -f 1 | sort -u))
 	(( ${#fprs[@]} > 0 )) || { printf "$FUNCNAME: Error: "$"No certificate for user '%s'.""\n" "$user" >&2 ; return 1 ;}
-	(( ${#fprs[@]} < 2 )) || { printf "$FUNCNAME: Error: "$"User '%s' match many certificates (%s).""\n" "$user" "${fprs[*]}" >&2 ; return 1 ;}
+	(( ${#fprs[@]} < 2 )) || { printf "$FUNCNAME: Error: "$"User '%s' match many (%d) certificates"" (%s).\n" "$user" ${#fprs[@]} "${fprs[*]}" >&2 ; return 1 ;}
 	user=${fprs[0]}
 
 	if [[ "$torev" || "$toadd" ]] ; then
@@ -1152,7 +1152,7 @@ OPTIONS:
   -i, --info              Output content of the associative array containing relevant metadata (may be evaluted with eval)
   -q, --quiet             Don't errput 'Info' or 'Notice' messages.
   -H, --homedir GNUPGHOME GnuPG home directory (default: ~/.gnupg). Environnement variable: \$GNUPGHOME
-  -A, --aaname VARNAME    If VARNAME is a reacheable associative array: fill it (confer --info)
+  -A, --aaname VARNAME    If VARNAME is a reacheable associative array: fill it (whithout cleaning known fields)
 							else: Output 'declare -A VARNAME=...'
 "
 	local varname fetch=1 info=0 quiet=0 isaa=0
@@ -1234,6 +1234,9 @@ OPTIONS:
 		fi
 	done <<<"${cardstatus}"
 
+	# Signature key on token may differs from main key, aka Certification key.
+	aaname[pgpid_Ckeyfpr]=$(gpg --homedir "$gpghome" --list-options show-only-fpr-mbox --list-key "${aaname[pgpid_Skeyfpr]:- ${aaname[pgpid_Ekeyfpr]:- ${aaname[pgpid_Akeyfpr]}}}" | grep -o -m1 "\<[0-9ABCDEF]\{40\}\>") || true
+
 	aaname[pgpid_email]="${emails[0]}"
 	(( $(sort -u <<<"${emails[@]}" | wc -l) < 2 )) || ((quiet)) || echo "$FUNCNAME: Notice:" $"supernumerary emails, skipping" "$(sort -u <<<"${emails[@]}" | grep -v "${emails[0]}") ..." >&2
 
@@ -1267,7 +1270,7 @@ OPTIONS:
 
 	! ((ret)) || return $ret
 
-	((quiet)) || printf "$FUNCNAME: Info: "$"Valid OpenPGP ID token"", pgpid_id='${aaname[pgpid_id]}'.\n" >&2
+	((quiet)) || printf "$FUNCNAME: Info: "$"Valid OpenPGP ID token"", pgpid_Ckeyfpr='${aaname[pgpid_Ckeyfpr]}', pgpid_id='${aaname[pgpid_id]}'.\n" >&2
 	return 0
 }
 
@@ -1289,8 +1292,8 @@ bl_pgpid_certify() {
 OPTIONS:
   -u, --use-privkey NAME|KEYID "$"Select private key to use. "$"Default: "$"Guess it from connected token, else ask.""
   -R, --revoke                 "$"Revoke your previous certifications on someone else's certificate.""
-  -G, --vouch                  "$"Take responsability for any (illegal) actions by the target. "$"Same as"" '--vouch-for ALL'. (Not implemented yet)
-  -g, --vouch-for DOMAIN       "$"Assume additional legal responsibilities on the target."" (Not implemented yet)
+  -G, --vouch                  "$"Take legal responsability for any actions by the target. "$"Same as"" '--vouch-for ALL'. (Not implemented yet)
+  -g, --vouch-for DOMAIN       "$"Assume some legal responsibilities on the target."" (Not implemented yet)
   -l, --local                  "$"« Non-exportable » certification. Pretty useless. Allow to less affect credibility.""
   -f, --force-sign-key         "$"Allow to unrevoke or to change vouching.""
   -k, --keyserver KEYSERVER    "$"If non-empty, receive and send updated certificate to this keyserver. "$"Default: ""$keyserv.
@@ -1332,7 +1335,7 @@ OPTIONS:
 	for ((;$#;)) ; do
 		if [[ "$1" =~ (${BL_PGPID_U4_REGEX}|${BL_PGPID_U5_REGEX}) ]] ; then
 			targetid=${BASH_REMATCH[0]}
-		elif [[ "${1^^}" == ^[ABCDEF0-9]{40}$ ]] ; then
+		elif [[ "${1^^}" =~ ^[ABCDEF0-9]{40}$ ]] ; then
 			targetfpr=${BASH_REMATCH[0]}
 		else
 			printf "$FUNCNAME: Error: "$"Unrecognized argument"" '$1.\n\n"$"Try '%s --help' for more information"".\n" "$name" >&2
@@ -1364,7 +1367,7 @@ OPTIONS:
 	fprs=($(gpg --homedir "$gpghome" --list-options show-only-fpr-mbox --list-key "$targetid" | cut -d ' '  -f 1 | sort -u))
 	(( ${#fprs[@]} > 0 )) || { printf "$FUNCNAME: Error: "$"No certificate for user '%s'.""\n" "$targetid" >&2 ; return 1 ;}
 	if (( ${#fprs[@]} >= 2 )) ; then
-		printf "$FUNCNAME: Info: "$"User '%s' match many certificates (%s).""\n" "$targetid" "${#fprs[@]}" >&2
+		printf "$FUNCNAME: Info: "$"User '%s' match many (%d) certificates"".\n" "$targetid" "${#fprs[@]}" >&2
 		[[ "$targetfpr" ]] || ifpr=$(bl_radiolist --output-index --text "Please select fingerprint" -- "${fprs[@]/%????????????????????/...}") || return $?
 	fi
 
