bl_pgpid_certify(): improve wording + bugfix: pgpid_Skeyfpr -> pgpid_Ckeyfpr

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -518,7 +518,7 @@ OPTIONS:
 }
 
 _bl_pgp_choose_seckeyid() {
-	local qtxt="Select KeyID (your OpenPGP certificate)"
+	local qtxt=$"Select KeyID (your OpenPGP certificate)"
 	local helpmsg="Usage: $FUNCNAME [NAME|U4|U5|EMAIL]
 Output keyid choosen from available (main) secrets keys.
 If there is only one available, output its keyid whithout asking.
@@ -759,12 +759,12 @@ bl_pgpid_gen_uid() {
 	((BL_PGPID_isprogram)) && name="$BL_PGPID_NAME ${FUNCNAME:9}" || name="$FUNCNAME"
 	local usage="Usage: $name [OPTIONS]... [UDID4]"
 	local helpmsg="
-Generate a 32bit Unix User ID, from 2^18 to (2^31)-2 ([$BL_PGPID_XUID_MIN,$BL_PGPID_XUID_MAX]).
-If UDID4 is not given, it will ask for surname, names and date of birth.
+"$"Generate a 32bit Unix User ID, from 2^18 to (2^31)-2"" ([$BL_PGPID_XUID_MIN,$BL_PGPID_XUID_MAX]).
+"$"If UDID4 is not given, it will ask for surname, names and date of birth.""
 
 OPTIONS:
-  -f, --free-input            Accept any input, not only valid OpenPGP ID string.
-  -F, --from FILE             Get input from first line of FILE (eg: fifo, tmpfs, /dev/stdin ...)
+  -f, --free-input            "$"Accept any input, not only valid OpenPGP ID string.""
+  -F, --from FILE             "$"Get input from first line of FILE (eg: fifo, tmpfs, /dev/stdin ...)""
 "
 	local freeinput=0 str_in u4h num
 	for ((;$#;)) ; do
@@ -791,7 +791,7 @@ OPTIONS:
 			freeinput=0
 		fi
 	elif [[ "$1" ]] ; then
-			printf "%s: Warning: option --from overide given argument '%s'...\n" "$FUNCNAME" "${1: 0:44}" >&2
+			printf "$FUNCNAME: Warning: "$"Option %s overide given argument '%s'""...\n" "--from" "${1: 0:44}" >&2
 	fi
 
 	if ((freeinput)) ; then
@@ -800,7 +800,7 @@ OPTIONS:
 	elif [[ "$str_in" =~ (${BL_PGPID_U4H_REGEX})${BL_PGPID_CO_REGEX} ]] ; then
 		u4h="${BASH_REMATCH[1]}=="
 	else
-		printf "%s: Error: No u4 string (hash) found in '%s'...\n" "$FUNCNAME" "${str_in: 0:50}" >&2
+		printf "$FUNCNAME: Error: "$"No u4 string (hash) found in '%s'""...\n" "${str_in: 0:50}" >&2
 		return 2
 	fi
 
@@ -1347,7 +1347,7 @@ OPTIONS:
 	if [[ -z "$keyid" ]] ; then
 		local -A cardinfo
 		bl_pgpid_token_check --homedir "$gpghome" --no-fetch --quiet --aaname cardinfo || true
-		[[ "${cardinfo[pgpid_Skeyfpr]}" ]] && keyid=${cardinfo[pgpid_Skeyfpr]} || keyid=$(_bl_pgp_choose_seckeyid --homedir "$gpghome")
+		[[ "${cardinfo[pgpid_Ckeyfpr]}" ]] && keyid=${cardinfo[pgpid_Ckeyfpr]} || keyid=$(_bl_pgp_choose_seckeyid --homedir "$gpghome" --text $"Private key to use ? (KeyID of your Certification Key)")
 	fi
 
 	# Get fpr for private key to use
