bl_pgpid_avatar(): also force avatar width to 180 pixel (180x180)

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -926,8 +926,8 @@ bl_pgpid_avatar() {
 	local helpmsg='
 '$"Extract or add image inside OpenPGP certificate."'
 '$"Missing NAME|KEYID|U4|U5 => KEYID of secret key may be asked interactively."'
-'$"New IMAGE should be 180 pixel height, or it will be resized."'
-'$"Ouput extracted *.jpg files inside working directory."'
+'$"New IMAGE should be 180x180 pixels, or it will be resized."'
+'$"Output path(s) of extracted image(s)."'
 
 '$"Options:"'
   -E, --extract-all           '$"Extract also all revoked or expired existing images from OpenPGP certificate."'
@@ -976,16 +976,16 @@ bl_pgpid_avatar() {
 	(( ${#fprs[@]} > 0 )) || { printf "$FUNCNAME: Error: "$"No certificate for %s"".\n" "'$user'" >&2 ; return 1 ;}
 
 	if [[ "$image" ]] ; then
-		local height
+		local -a size
 		# copy image to read it once if it was a fifo or /dev/stdin ...
 		cat "$image" > "$tmpdir/origin.image" || { printf "%s: Error: Can't retrieve image file %s.\n" "$FUNCNAME" "${image@Q}" >&2 ; return 1 ;}
-		height=$(gm identify -format "%h" "$tmpdir/origin.image") || { printf "$FUNCNAME: Error: "$"Unable to identify image"" ${image@Q}.\n" >&2 ; return 1 ;}
-		if ((height==180)) ; then
-			# Image has already the expected height, don't alter it.
+		size=($(gm identify -format "%w %h" "$tmpdir/origin.image")) || { printf "$FUNCNAME: Error: "$"Unable to identify image"" ${image@Q}.\n" >&2 ; return 1 ;}
+		if ((size[0]==180 && size[1]==180)) ; then
+			# Image has already the expected size, don't alter it.
 			mv "$tmpdir/origin.image" "$tmpdir/new.jpg" || return $?
 		else
 			# Resize
-			gm convert -geometry x180 "$tmpdir/origin.image" jpeg:"$tmpdir/new.jpg" || { printf "$FUNCNAME: Error: "$"Unable to resize image"" ${image@Q}.\n" >&2 ; return 1 ;}
+			gm convert -geometry "180^" -gravity center -extent 180 -strip "$tmpdir/origin.image" jpeg:"$tmpdir/new.jpg" || { printf "$FUNCNAME: Error: "$"Unable to resize image"" ${image@Q}.\n" >&2 ; return 1 ;}
 			rm "$tmpdir/origin.image" || return $?
 		fi
 	fi
