improve in-source doc, generate manpages

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -529,19 +529,19 @@ bl_pgpid_mrz_to_u4() {
 	((BL_PGPID_isprogram)) && name="$BL_PGPID_NAME ${FUNCNAME:9}" || name="$FUNCNAME"
 	local usage="Usage: $name [OPTIONS]... MRZ..."
 	local helpmsg="
-Convert the Machine Readable Zone of an icao9303 passport to an udid4 (aka 'u4').
+Convert the Machine Readable Zone of an icao9303 passport to its u4 identifier.
 
 Option:
   -u, --uncheck                Dont verify checksums
   -d, --birth-date YYYY-MM-DD  Birth date, expected format : Year-Month-Day (for people born 100+ years ago)
 
-WARNING: mrz data may be irrelevant to generate udid4. eg:
+WARNING: mrz data may be irrelevant to generate u4 identifier. eg:
          * Surname or given names may be incomplete (cut bc exceed mrz size)
          * Surname or given names may differs from those given at birth (marriage, gender change, etc.)
          * Surname or given names transliteration may have change over time
          * Year of birth date is only written with 2 digits (and people may live longer than 100 years)
          * Humans may have done error on birth date, surname or given names.
-By the way, there are ~80% chance that an icao9303 MRZ allow to generate a correct udid4.
+By the way, there are ~80% chance that an icao9303 MRZ allow to generate a correct u4 identifier.
 People have to check, and fix when NOK.
 "
 
@@ -597,8 +597,8 @@ bl_pgpid_gen_u4() {
 	((BL_PGPID_isprogram)) && name="$BL_PGPID_NAME ${FUNCNAME:9}" || name="$FUNCNAME"
 	local usage="Usage: $name [OPTIONS]... [MRZ]..."
 	local helpmsg="
-Generate udid4. Missing inputs are asked interactively.
-You may pass the Machine Readable Zone of an international passport as argument, but there are ~20% chances that generated udid4 is incorrect.
+Generate u4 identifier. Missing inputs are asked interactively.
+You may pass the Machine Readable Zone of an international passport as argument, but there are ~20% chances that generated *u4* is incorrect.
 
 Options:
   -s, --surname SURNAME            Surname/family name at birth
@@ -705,7 +705,7 @@ bl_pgpid_gen_uid() {
 #    Return value $?: 0 (OK)
 #
 #   If we let 4294967294, 4294967293 and id under 2^18 (< 262144), for some futur usage/convention,
-#   then we can use range 262144 to 4294967292, to get an almost unique Unix User ID from unique foopgp User ID (udid4,...)
+#   then we can use range 262144 to 4294967292, to get an almost unique Unix User ID from unique foopgp identifier (u4,...)
 #
 #   Confer https://www.debian.org/doc/debian-policy/ch-opersys.html#users-and-groups
 #
@@ -760,7 +760,7 @@ Options:
 	elif [[ "$str_in" =~ (${BL_PGPID_U4H_REGEX})${BL_PGPID_CO_REGEX} ]] ; then
 		u4h="${BASH_REMATCH[1]}=="
 	else
-		printf "%s: Error: No udid4 (hash) found in '%s'...\n" "$FUNCNAME" "${str_in: 0:50}" >&2
+		printf "%s: Error: No u4 identifier (hash) found in '%s'...\n" "$FUNCNAME" "${str_in: 0:50}" >&2
 		return 2
 	fi
 
@@ -1207,7 +1207,7 @@ if [[ "$BASH_SOURCE" == "$0" ]] ; then
 	# run as a program
 	declare -r BL_PGPID_isprogram=1
 
-	BL_PGPID_usage="Usage: $BASH_SOURCE [OPTIONS]... ACTION [ACTION_ARGUMENTS]..."
+	BL_PGPID_usage="Usage: $BASH_SOURCE [MAIN_OPTIONS]... ACTION [OPTIONS]... [ARGUMENTS]..."
 	BL_PGPID_shelpmsg="
   -h, --help               show help and exit
   -V, --version            show version and exit
@@ -1216,7 +1216,7 @@ Actions:
 $(for f in "${BL_PGPID_FUNCTIONS[@]}" ; do printf "   %-19s%s\n" "${f:9}" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
 
 All actions support a --help options, eg:
-$ $BASH_SOURCE ACTION --help
+$ $BASH_SOURCE ${BL_PGPID_FUNCTIONS:9} --help
 
 $BL_PGPID_NAME is also bash library, see:
 $ source $BASH_SOURCE --help
@@ -1224,7 +1224,7 @@ $ source $BASH_SOURCE --help
 else
 	# run as a library (source $0)
 
-	BL_PGPID_usage="Usage: source $BASH_SOURCE [OPTIONS]..."
+	BL_PGPID_usage="Usage: source $BASH_SOURCE [MAIN_OPTIONS]..."
 
 	BL_PGPID_shelpmsg="
       --bash-completion    set completion for $BASH_SOURCE program and return (without loading anything else)
@@ -1237,9 +1237,9 @@ Reminder: when used as a library, all functions calls share the same environment
 fi
 
 BL_PGPID_chelpmsg="
-Generate foopgp identifiers, like *udid4* to identify world-wide humans, or a fixed Unix User ID for each of them.
+Generate and manage (foo)pgp id : u4 identifiers (for world-wide humans), fixed system *uid*, OpenPGP certificate, etc.
 
-Options:
+Main options:
   -f, --frontend PROGRAM   select a frontend program {NONE,whiptail,dialog} (environment var: BL_INTERACTIVE_FRONTEND)"
 
 ### Init ###
