bl_pgpid_get(): fix 1 bug + manage wkd + manage multiple input parameters

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -576,16 +576,18 @@ bl_pgpid_get() {
 OPTIONS:
   -F, --fingerprint           "$"Output only fingerprints.""
   -E, --email                 "$"Output only emails.""
-  -s, --secret                "$"Search through local secret keys instead of public certificate.""
+  -l, --local                 "$"Don't refresh certificates from keyservers or Web Key Directories.""
+  -s, --secret                "$"Search through local secret keys instead of public certificate."" - "$"Imply --local.""
   -m, --errexit-g=1           "$"Return an error if there is more than one (1) entry."" - "$"You may replace '1' by an other number.""
   -M, --max-from-keyserv MAX  "$"Set maximum matching certificates to receive from keyservers. "$"Default: ""$maxfromks
   -T, --ownertrust THRESHOLD  "$"Only output fingerprint with ownertrust greater or equal to THRESHOLD."" (Not implemented)
   -H, --homedir GNUPGHOME     "$"GnuPG home directory (default: ~/.gnupg). "$"Environnement variable: ""\$GNUPGHOME
-  -K, --keyservers KEYSERVERS "$"If non-empty, search and refresh certificates from this keyservers. "$"Default: ""
+  -K, --keyservers KEYSERVERS "$"Search and refresh certificates from this keyservers. "$"Default: ""
 $(printf -- "%80s\n" ${keyservs[@]})
 "
 	local onlyfpr=0 onlymbox=0
 	local gpgaction="--list-keys"
+	local wkdcmd="gpg --auto-key-locate clear,wkd --locate-external-keys"
 	local errexit=$(getconf INT_MAX)
 	local gpghome=${GNUPGHOME:-~/.gnupg}
 	for ((;$#;)) ; do
@@ -595,7 +597,9 @@ $(printf -- "%80s\n" ${keyservs[@]})
 			-E|--mbox|--email)
 				onlyfpr=0 onlymbox=1 ;;
 			-s|--secret)
-				gpgaction="--list-secret-keys"
+				gpgaction="--list-secret-keys" ;&
+			-l|--local)
+				wkdcmd="true"
 				keyservs=() ;;
 			-m|--errexit|--errexit-g)
 				errexit=1 ;;
@@ -624,10 +628,10 @@ $(printf -- "%80s\n" ${keyservs[@]})
 	done
 
 	[[ "$1" ]] || { printf "$usage\n" >&2 ; return 2 ; }
-	local user=$1
+	local users=("$@")
 
 	if ((maxfromks>0)) ; then
-		local -a ksfprs
+		local -a ksfprs user
 		local scheme serv port path ksurl
 		for keyserv in ${keyservs[@]} ; do
 			[[ "$keyserv" =~ // ]] || keyserv="hkps://$keyserv"
@@ -643,25 +647,28 @@ $(printf -- "%80s\n" ${keyservs[@]})
 				[[ "${scheme:3:1}" == s ]] && port=443 || port=11371
 			fi
 			ksurl="http${scheme:3:1}://${serv}:${port}${path}/pks/lookup"
-			ksfprs=($(curl --no-progress-meter --location --get --data-urlencode 'op=index' --data-urlencode "search=$user" --data-urlencode "options=mr" "$ksurl" | sed -n 's,^pub:\([[:xdigit:]]*\):.*,\1,p'))
-			if [[ -z "${ksfprs[@]}" ]] ; then
-				printf "$FUNCNAME: Notice: "$"No certificate for %s on %s.""\n" "'$user'" "'$keyserv'" >&2
-				continue
-			elif ((${#ksfprs[@]} <= maxfromks )) ; then
-				curl --no-progress-meter --location --get --data-urlencode 'op=get' --data-urlencode "search=$user" --data-urlencode "options=mr" "$ksurl" | gpg --homedir "$gpghome" --import-options import-clean --import
-			else
-				local i
-				for ((i=0;i<maxfromks;i++)) ; do
-					curl --no-progress-meter --location --get --data-urlencode 'op=get' --data-urlencode "search=0x${ksfprs[i]}" --data-urlencode "options=mr" "$ksurl" | gpg --homedir "$gpghome" --import
-				done
-			fi
+			for user in "${users[@]}" ; do
+				ksfprs=($(curl --no-progress-meter --location --get --data-urlencode 'op=index' --data-urlencode "search=$user" --data-urlencode "options=mr" "$ksurl" | sed -n 's,^pub:\([[:xdigit:]]*\):.*,\1,p'))
+				if [[ -z "${ksfprs[@]}" ]] ; then
+					printf "$FUNCNAME: Notice: "$"No certificate for %s on %s.""\n" "'$user'" "'$keyserv'" >&2
+					continue
+				elif ((${#ksfprs[@]} <= maxfromks )) ; then
+					curl --no-progress-meter --location --get --data-urlencode 'op=get' --data-urlencode "search=$user" --data-urlencode "options=mr" "$ksurl" | gpg --homedir "$gpghome" --import-options import-clean --import || true
+				else
+					local i
+					for ((i=0;i<maxfromks;i++)) ; do
+						curl --no-progress-meter --location --get --data-urlencode 'op=get' --data-urlencode "search=0x${ksfprs[i]}" --data-urlencode "options=mr" "$ksurl" | gpg --homedir "$gpghome" --import
+					done
+				fi
+			done
 		done
 	fi
+	$wkdcmd --homedir "$gpghome" $(grep -o --extended-regexp "$BL_INTERACTIVE_EMAIL_REGEX" <<<"${users[@]}") || true
 
 	local -a fprmboxs fprs
-	readarray -t fprmboxs < <(gpg --homedir "$gpghome" --list-options show-only-fpr-mbox $gpgaction "$user")
+	readarray -t fprmboxs < <(gpg --homedir "$gpghome" --list-options show-only-fpr-mbox $gpgaction "${users[@]}")
 	fprs=($(printf -- "%s\n" "${fprmboxs[@]%% *}" | sort -u))
-	(( ${#fprs[@]} > 0 )) || { printf "$FUNCNAME: Error: "$"No certificate for user"" '%s'.\n" "$user" >&2 ; return 141 ;}
+	(( ${#fprs[@]} > 0 )) || { printf "$FUNCNAME: Error: "$"No certificate for"" '%s'...\n" "$users" >&2 ; return 141 ;}
 	if ((onlyfpr)) ; then
 		printf -- "%s\n" "${fprs[@]}"
 	elif ((onlymbox)) ; then
@@ -684,7 +691,7 @@ $(printf -- "%80s\n" ${keyservs[@]})
 
 	if ((${#fprs[@]} != 1 )) ; then
 		(( ${#fprs[@]} <= errexit )) && local errlvl="Notice" || local errlvl="Error"
-		printf "$FUNCNAME: $errlvl: "$"%s certificates for %s." "${#fprs[@]}" "'$user'" >&2
+		printf "$FUNCNAME: $errlvl: "$"%s certificates for %s input params." "${#fprs[@]}" "${#users[@]}" >&2
 		(( ${#fprs[@]} >= maxfromks )) && printf " "$"Some public certificates may be missing.""\n" >&2 || printf "\n" >&2
 	fi
 	(( ${#fprs[@]} <= errexit )) || return 7
@@ -1229,7 +1236,7 @@ $(printf -- "%80s\n" ${keyservs[@]})
 
 	# Check that $user match only one certificate
 	local fprs
-	fprs=($(bl_pgpid_get --fpr --errexit-g=1 --homedir "$gpghome" --keyservers "" "$user")) || return $?
+	fprs=($(bl_pgpid_get --fingerprint --errexit-g=1 --homedir "$gpghome" --local "$user")) || return $?
 	user=${fprs[0]}
 
 	if [[ "$torev" || "$toadd" ]] ; then
@@ -1530,7 +1537,7 @@ $(printf -- "%80s\n" ${keyservs[@]})
 
 	# get fingerprints for certificate to certify
 	local fprs ifpr=0 uids
-	fprs=($(bl_pgpid_get --fpr --homedir "$gpghome" --keyservers "${keyservs[*]}" "$targetid")) || return 141
+	fprs=($(bl_pgpid_get --fingerprint --homedir "$gpghome" --keyservers "${keyservs[*]}" "$targetid")) || return 141
 	if (( ${#fprs[@]} >= 2 )) ; then
 		printf "$FUNCNAME: Info: "$"User '%s' match many (%d) certificates"".\n" "$targetid" "${#fprs[@]}" >&2
 		[[ "$targetfpr" ]] || ifpr=$(bl_radiolist --output-index --text $"Please select key fingerprint" -- "${fprs[@]/#????????????????????????/...}") || return 140
