bl-pgpid: test, fix and improve bl_pgpid_gen_uid()

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -68,6 +68,9 @@ declare -r BL_PGPID_CO_REGEX="e[_-][0-9]{2}\.[0-9]{2}[_-][01][0-9]{2}\.[0-9]{2}"
 declare -r BL_PGPID_U4H_REGEX="[a-zA-Z0-9_-]{22}"
 declare -r BL_PGPID_U4_REGEX="${BL_PGPID_U4H_REGEX}${BL_PGPID_CO_REGEX}"
 
+declare -r BL_PGPID_XUID_MIN=$((1<<18))
+declare -r BL_PGPID_XUID_MAX=$(((1<<32)-4))
+
 declare -Ar BL_PGPID_COORDINATES=(
 [ABW]="e_12.52-069.98 Aruba"
 [AFG]="e_33.84_066.00 Afghanistan"
@@ -673,22 +676,27 @@ bl_pgpid_gen_uid() {
 #    useradd warning: test's uid -2 outside of the UID_MIN 1000 and UID_MAX 60000 range.
 #    Return value $?: 0 (OK)
 #
-#   If we let 4294967294, 4294967293 and 65535, for some futur usage/convention,
-#   So we can use range 65536 to 4294967292, to get an almost unique Unix User ID from unique foopgp User ID (udid4,...)
+#   If we let 4294967294, 4294967293 and id under 2^18 (< 262144), for some futur usage/convention,
+#   then we can use range 262144 to 4294967292, to get an almost unique Unix User ID from unique foopgp User ID (udid4,...)
 #
-#   Which make 4294901756 slots, ~= about half of the actual human population (~8 billions).
+#   Which make 4294705148 slots, ~= about half of the actual human population (~8 billions).
+#   Constants: BL_PGPID_XUID_MIN and BL_PGPID_XUID_MAX
 
 	local name
 	((BL_PGPID_isprogram)) && name="$BL_PGPID_NAME ${FUNCNAME:9}" || name="$FUNCNAME"
-	local usage="Usage: $name [UDID4]"
+	local usage="Usage: $name [OPTIONS] [UDID4]"
 	local helpmsg="
-Generate a 64bit Unix User ID.
+Generate a 32bit Unix User ID, from 2^18 to (2^32)-4 ([$BL_PGPID_XUID_MIN,$BL_PGPID_XUID_MAX]).
 If UDID4 is not given, it will ask for surname, names and date of birth.
-You may pass a foopgp UDID4 as an argument, as Unix uid is calculated from it.
+You may pass a foopgp UDID4 as an argument, as ouput is calculated from it.
+
+Options:
+	-f, --free-input            Accept any input, not only string containing a foopgp UDID4.
 "
-	local u4 u4h num
+	local freeinput=0 str_in u4h num
 	for ((;$#;)) ; do
 		case "$1" in
+			-f|--free-input) freeinput=1 ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
 			-V|--version) printf "%s %s\n" "$name" "$BL_PGPID_VERSION" ; return ;;
 			--) shift ; break ;;
@@ -699,20 +707,24 @@ You may pass a foopgp UDID4 as an argument, as Unix uid is calculated from it.
 	done
 
 	if [[ "$1" ]] ; then
-		# If an UDID4 is passed as arguments
-		u4="$1"
+		# If an input is passed as arguments
+		str_in="$*"
 	else
-		u4="$(bl_pgpid_gen_u4 --birth-country FRA)=="
+		str_in="$(bl_pgpid_gen_u4 --birth-country FRA)=="
+		freeinput=0 # --free-input is non-sense if no imput has been given in $*.
 	fi
 
-	if [[ "$u4" =~ ${BL_PGPID_U4H_REGEX} ]] ; then
-		u4h="${BASH_REMATCH[0]}"
+	if ((freeinput)) ; then
+		u4h="$(echo "$str_in" | md5sum | xxd -r -p | basenc --base64url)"
+		echo "$u4h"
+	elif [[ "$str_in" =~ ${BL_PGPID_U4H_REGEX} ]] ; then
+		u4h="${BASH_REMATCH[0]}=="
 	else
-		printf "%s: Error: No udid4 (hash) found in '%s'...\n" "$name" "${u4: 0:44}" >&2
+		printf "%s: Error: No udid4 (hash) found in '%s'...\n" "$name" "${str_in: 0:44}" >&2
 		return 2
 	fi
 
-	num=$(bl_pgpid_2num --input-encoding base64 4294901756 <<<"$u4h==") && echo $((num+65536))
+	num=$(bl_pgpid_2num --input-encoding base64url $((BL_PGPID_XUID_MAX - BL_PGPID_XUID_MIN)) <<<"$u4h") && echo $((num + BL_PGPID_XUID_MIN))
 }
 
 ### General Help Messages (and set -e if program) ###
