update doc: READMEs man --help

diff --git a/bin/bl-pgpid b/bin/bl-pgpid
--- a/bin/bl-pgpid
+++ b/bin/bl-pgpid
@@ -550,20 +550,20 @@ bl_pgpid_mrz_to_u4() {
 	((BL_PGPID_isprogram)) && name="$BL_PGPID_NAME ${FUNCNAME:9}" || name="$FUNCNAME"
 	local usage="Usage: $name [OPTIONS]... [MRZ]..."
 	local helpmsg="
-Calculate and output a OpenPGP ID u4 string from the Machine Readable Zone of an icao9303 passport.
+Calculate and output a OpenPGP ID u4, from the Machine Readable Zone of an icao9303 passport.
 If MRZ is not passed as argument, it will we read from STDIN.
 
 Option:
   -d, --birth-date YYYY-MM-DD  Birth date, expected format : Year-Month-Day (for people born 100+ years ago)
   -u, --uncheck                Change some MRZ errors to warnings (only if you really know what you do !).
 
-WARNING: mrz data may be irrelevant to generate u4 identifier. eg:
+WARNING: mrz data may be irrelevant to generate u4 string. eg:
          * Surname or given names may be incomplete (cut bc exceed mrz size)
          * Surname or given names may differs from those given at birth (marriage, gender change, etc.)
          * Surname or given names transliteration may have change over time
          * Year of birth date is only written with 2 digits (and people may live longer than 100 years)
          * Humans may have done error on birth date, surname or given names.
-By the way, there are ~80% chance that an icao9303 MRZ allow to generate a correct u4 identifier.
+By the way, there are ~80% chance that an icao9303 MRZ allow to generate a correct u4 string.
 People have to check, and fix when NOK.
 "
 
@@ -619,7 +619,7 @@ bl_pgpid_gen_u4() {
 	((BL_PGPID_isprogram)) && name="$BL_PGPID_NAME ${FUNCNAME:9}" || name="$FUNCNAME"
 	local usage="Usage: $name [OPTIONS]... [MRZ]..."
 	local helpmsg="
-Generate u4 identifier. Missing inputs are asked interactively.
+Generate OpenPGP ID u4 string. Missing inputs are asked interactively.
 You may pass the Machine Readable Zone of an international passport as argument, but there are ~20% chances that generated *u4* is incorrect.
 
 Options:
@@ -729,7 +729,7 @@ bl_pgpid_gen_uid() {
 #    Return value $?: 0 (OK)
 #
 #   If we let 4294967294, 4294967293 and id under 2^18 (< 262144), for some futur usage/convention,
-#   then we can use range 262144 to 4294967292, to get an almost unique Unix User ID from unique foopgp identifier (u4,...)
+#   then we can use range 262144 to 4294967292, to get an almost unique Unix User ID from unique OpenPGP ID string (u4,...)
 #
 #   Confer https://www.debian.org/doc/debian-policy/ch-opersys.html#users-and-groups
 #
@@ -747,7 +747,7 @@ Generate a 32bit Unix User ID, from 2^18 to (2^31)-2 ([$BL_PGPID_XUID_MIN,$BL_PG
 If UDID4 is not given, it will ask for surname, names and date of birth.
 
 Options:
-  -f, --free-input            Accept any input, not only string containing a foopgp UDID4.
+  -f, --free-input            Accept any input, not only valid OpenPGP ID string.
   -F, --from FILE             Get input from first line of FILE (eg: fifo, tmpfs, /dev/stdin ...)
 "
 	local freeinput=0 str_in u4h num
@@ -784,7 +784,7 @@ Options:
 	elif [[ "$str_in" =~ (${BL_PGPID_U4H_REGEX})${BL_PGPID_CO_REGEX} ]] ; then
 		u4h="${BASH_REMATCH[1]}=="
 	else
-		printf "%s: Error: No u4 identifier (hash) found in '%s'...\n" "$FUNCNAME" "${str_in: 0:50}" >&2
+		printf "%s: Error: No u4 string (hash) found in '%s'...\n" "$FUNCNAME" "${str_in: 0:50}" >&2
 		return 2
 	fi
 
@@ -797,7 +797,7 @@ bl_pgpid_gen_key() {
 	local usage="Usage: $name [OPTIONS]... EMAIL"
 	local keyserv=${BL_PGPID_KEYSERVERS[0]}
 	local helpmsg="
-Generate an OpenPGP key pair (public and secret) according to foopgp standards.
+Generate an OpenPGP key pair (public and secret) according to OpenPGP ID standards.
 Missing inputs are asked interactively.
 Output 3 lines for each fingerprints :
 * main key (Sign Certify)
@@ -1289,7 +1289,7 @@ Reminder: when used as a library, all functions calls share the same environment
 fi
 
 BL_PGPID_chelpmsg="
-Generate and manage (foo)pgp id : u4 identifiers (for world-wide humans), fixed system *uid*, OpenPGP certificate, etc.
+Generate and manage OpenPGP ID: u4 or u5 strings, fixed system *uid*, OpenPGP certificate, etc.
 
 Main options:
   -f, --frontend PROGRAM   select a frontend program {NONE,whiptail,dialog,zenity} (environment var: BL_INTERACTIVE_FRONTEND)"
