fix commit 19ce12699866c0037d9a0ead85fa9e3d915468c4 + bl-qrkey : fix min splitn

diff --git a/bin/bl-qrkey b/bin/bl-qrkey
--- a/bin/bl-qrkey
+++ b/bin/bl-qrkey
@@ -197,8 +197,8 @@ Options:
 		return 1
 	fi
 
-	if ((splitn<2)) ; then
-		printf "%s: Error: splits number (%d) can't be lower than 2.\n" "$FUNCNAME" "$splitn" >&2
+	if ((splitn<3)) ; then
+		printf "%s: Error: splits number (%d) can't be lower than 3.\n" "$FUNCNAME" "$splitn" >&2
 		return 2
 	fi
 
