bl_qrkey_totoken(): improve login field (u4|u5)

diff --git a/bin/bl-qrkey b/bin/bl-qrkey
--- a/bin/bl-qrkey
+++ b/bin/bl-qrkey
@@ -804,7 +804,7 @@ Options:
 	[[ "$lang" =~ ^[abcdefghijklmnopqrstuvwxyz]{2}$ ]] || { printf "%s: Warning: only 2 lower case ASCII letters can define prefered language, fallback to 'en'.\n" "$FUNCNAME" >&2 ; lang=en ;}
 
 	local keyid secstatus
-	local -a seckeyids emails udid4
+	local -a seckeyids emails ids
 
 	mapfile -t seckeyids < <(_bl_pgp_get_seckeyid --exportable --homedir "$gpghome")
 	((${#seckeyids[@]}>0)) || { printf "%s: Error: No OpenPGP secret to move (from %s).\n" "$FUNCNAME" "$gpghome" >&2 ; return 1 ; }
@@ -817,12 +817,16 @@ Options:
 
 	# Check and get metadata
 	secstatus=$(gpg --quiet --homedir "$gpghome" --list-secret-keys "$keyid") || return $?
-	#  replace eventual keyID (short) by its keyFPR (longest)
+
+	# Replace eventual keyID (short) by its keyFPR (longest)
 	keyid=$(grep -o -m1 "\<[0-9ABCDEF]\{40\}\>" <<<"${secstatus}") || { printf "%s: Error: Can't get fingerprint (maybe due to incompatible gpg's version).\n" "$FUNCNAME" >&2 ; return 1 ; }
+
 	emails=($(sed --silent --regexp-extended "s,^uid.*[<[:space:]](${BL_INTERACTIVE_EMAIL_REGEX}).*,\1,p" <<<"${secstatus}"))
 	[[ "$emails" ]] || { printf "%s: Error: No email for OpenPGP key '%s'.\n" "$FUNCNAME" "$keyid" >&2 ; return 1 ; }
-	#  don't error if there is no pgp_id. TODO: manage also u5.
-	udid4=($(sed --silent --regexp-extended "s,.*4.?(${BL_PGPID_U4_REGEX}).*,\1,p" <<<"${secstatus}"))
+
+	# Don't error if there is no pgp_id
+	ids=($(sed --silent --regexp-extended "s,.*4.?(${BL_PGPID_U4_REGEX}).*,u4\1,p ; s,.*5.?(${BL_PGPID_U5_REGEX}).*,u5\1,p" <<<"${secstatus}" | sort -u))
+	(( ${#ids[@]} < 2 )) || { printf "%s: Error: supernumerary %s (%s)\n" "$FUNCNAME" "id" "${ids[*]}" >&2 ; return 1 ;}
 
 	grep -q "${keyid: 24}" <<<"${seckeyids[@]}" || { printf "%s: Error: No OpenPGP secrets for key '%s' (in %s).\n" "$FUNCNAME" "${keyid}" "$gpghome" >&2 ; return 1 ; }
 
@@ -848,7 +852,7 @@ Options:
 
 	printf "%s: Notice: Configuring OpenPGP security token...\n" "$FUNCNAME" >&2
 
-	echo -e "admin\nlogin\nid=u4${udid4[0]}\nurl\nhttps://${hkpsserv}/pks/lookup?op=get&search=0x${keyid}\nlang\n$lang\nname\n${emails[0]}\n${username}\n" | \
+	echo -e "admin\nlogin\n${ids[0]}\nurl\nhttps://${hkpsserv}/pks/lookup?op=get&search=0x${keyid}\nlang\n$lang\nname\n${emails[0]}\n${username}\n" | \
 	gpg --homedir "$gpghome" --command-fd 0 --batch --pinentry-mode loopback --passphrase "12345678" --card-edit 2> >( $gpgfilter ) || { printf "Setting OpenPGP card holder FAIL ($?)\n" >&2 ; return 1 ;}
 
 	echo -e "admin\nkey-attr\n2\n1\n2\n1\n2\n1\nquit" | \
