shellcheck

diff --git a/bl-interactive b/bl-interactive
--- a/bl-interactive
+++ b/bl-interactive
@@ -16,6 +16,12 @@
 #    You should have received a copy of the GNU Lesser General Public License
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
+# shellcheck disable=SC2013 # To read lines rather than words
+# shellcheck disable=SC2046 # Quote this to prevent word splitting
+# shellcheck disable=SC2086 # Double quote warning
+# shellcheck disable=SC2128 # expanding array without index warning
+# shellcheck disable=SC2162 # Read without -r
+
 
 if [[ "$1" == --bash-completion ]] ; then
 	BL_tmp_a="$("$BASH_SOURCE" --help | sed -n 's,^   \([a-z_-]\+\>\).*,\1,p' )"
@@ -41,7 +47,7 @@ if [[ "$1" == --bash-completion ]] ; then
 		esac
 		case $cur in
 			-*)
-				if a=$(grep -o "\<\('$(echo $BL_tmp_a | sed 's, ,\\|,g')'\)\>" <<< "${COMP_WORDS[@]}") ; then
+				if a=$(grep -o "\<\('${BL_tmp_a//$'\n'/\\|}'\)\>" <<< "${COMP_WORDS[@]}") ; then
 					COMPREPLY=( $(compgen -W "$coptions ${aoptions[$a]}" -- $cur ) )
 					return 0
 				fi
@@ -49,7 +55,7 @@ if [[ "$1" == --bash-completion ]] ; then
 				return 0 ;;
 		esac
 		# complete actions if none in ${COMP_WORDS[@]}
-		grep -q "\<\('$(echo $BL_tmp_a | sed 's, ,\\|,g')'\)\>" <<< "${COMP_WORDS[@]}" || COMPREPLY=( $(compgen -W "$actions" -- $cur ) )
+		grep -q "\<\('${BL_tmp_a//$'\n'/\\|}'\)\>" <<< "${COMP_WORDS[@]}" || COMPREPLY=( $(compgen -W "$actions" -- $cur ) )
 		return 0
 	}'
 	unset BL_tmp_a BL_tmp_o
@@ -66,7 +72,8 @@ fi
 
 ### Constants ###
 
-declare -r BL_INTERACTIVE_NAME="$(basename $(readlink -f "$BASH_SOURCE") )"
+BL_INTERACTIVE_NAME="$(basename "$(readlink -f "$BASH_SOURCE")" )"
+declare -r BL_INTERACTIVE_NAME
 declare -r BL_INTERACTIVE_VERSION="0.0.1"
 
 
@@ -75,10 +82,10 @@ declare -r BL_INTERACTIVE_VERSION="0.0.1"
 _bl_interactive_parseoptions() {
 	for ((;$#;)) ; do
 		case "$1" in
-			-h|--help) printf "$BL_INTERACTIVE_usage\n$BL_INTERACTIVE_chelpmsg\n$BL_INTERACTIVE_shelpmsg\n" ; return 2 ;;
-			-V|--version) printf "$BL_INTERACTIVE_NAME $BL_INTERACTIVE_VERSION\n" ; return 2 ;;
+			-h|--help) printf "%s\n%s\n%s\n" "$BL_INTERACTIVE_usage" "$BL_INTERACTIVE_chelpmsg" "$BL_INTERACTIVE_shelpmsg" ; return 2 ;;
+			-V|--version) printf "%s %s\n" "$BL_INTERACTIVE_NAME" "$BL_INTERACTIVE_VERSION" ; return 2 ;;
 			--) shift ; break ;;
-			-*) printf "$BL_INTERACTIVE_NAME: unrecognized option '$1'\n$BL_INTERACTIVE_usage\nTry '$BASH_SOURCE --help' for more information.\n" >&2 ; return 2 ;;
+			-*) printf "%s: unrecognized option '%s'\n\nTry '%s --help' for more information.\n" "$BL_INTERACTIVE_NAME" "$1" "$BASH_SOURCE" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
@@ -109,12 +116,12 @@ Options:
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
 			-V|--version) echo "$FUNCNAME $BL_INTERACTIVE_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "$FUNCNAME: Error: unrecognized option '%s'\nTry '$name --help' for more information.\n" "$1" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
 	done
-	question=" $@ (y/n)"
+	question=" $* (y/n)"
 	[[ -z "$def" ]] || question+=" [$def]"
 
 	while true ; do
@@ -153,28 +160,28 @@ Options:
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
 			-V|--version) echo "$FUNCNAME $BL_INTERACTIVE_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "$FUNCNAME: Error: unrecognized option '%s'\nTry '$name --help' for more information.\n" "$1" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
 	done
 	n=$#
-	((n)) || { printf "$FUNCNAME: Error: need items\nTry '$name --help' for more information.\n" >&2 ; return 1 ; }
-	printf "$pr" >&2
+	((n)) || { printf "%s: Error: need items\nTry '%s --help' for more information.\n" "$FUNCNAME" "$name" >&2 ; return 1 ; }
+	printf "%s" "$pr" >&2
 	for ((i=0;i<n;)) ; do
 		if ((i%nperline)) ; then
 			printf "\t\t" >&2
 		else
 			printf "\n\t" >&2
 		fi
-		printf "$((++i))) $1" >&2
+		printf "%d) %s" "$((++i))" "$1" >&2
 		shift
 	done
 	echo >&2
 	while ((ret<1 || ret>n)) ; do
 		read -p "Reply (1-$n) ? " ret
 	done
-	echo $ret
+	echo "$ret"
 }
 
 
@@ -188,7 +195,7 @@ if [[ "$BASH_SOURCE" == "$0" ]] ; then
 	BL_INTERACTIVE_usage="Usage: $BASH_SOURCE [OPTIONS]... ACTION [ACTION_ARGUMENTS]..."
 	BL_INTERACTIVE_shelpmsg="
 Actions:
-$(for f in $(sed -n 's,^\(bl_[^(]*\)().*, \1,p' "$BASH_SOURCE") ; do printf "   %-19s%s\n" "$(echo ${f:3} | tr '_' '-')" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
+$(for f in $(sed -n 's,^\(bl_[^( ]*\) *().*, \1,p' "$BASH_SOURCE") ; do printf "   %-19s%s\n" "$(echo ${f:3} | tr '_' '-')" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
 
 $BL_INTERACTIVE_NAME is also bash library, see:
 $ source $BASH_SOURCE --help"
@@ -201,7 +208,7 @@ else
       --bash-completion    set completion for $BASH_SOURCE program and return (without loading anything else)
 
 Functions:
-$(for f in $(sed -n 's,^\(bl_[^(]*\)().*, \1,p' "$BASH_SOURCE") ; do printf "   %-19s%s\n" "$f" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
+$(for f in $(sed -n 's,^\(bl_[^( ]*\) *().*, \1,p' "$BASH_SOURCE") ; do printf "   %-19s%s\n" "$f" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
 
 Reminder: when used as a library, all functions calls share the same environment variables, i.e. the same global options."
 fi
@@ -223,13 +230,13 @@ _bl_interactive_parseoptions "$@"
 
 ### Run ###
 
-if grep -q "^bl_${1//-/_}()" "$BASH_SOURCE" ; then
+if grep -q "^bl_${1//-/_} *()" "$BASH_SOURCE" ; then
 	function="bl_${1//-/_}"
 	shift
 	$function "$@"
 	exit $?
 else
-	printf "$BL_INTERACTIVE_NAME: unrecognized action '$1'\n$BL_INTERACTIVE_usage\nTry '$BASH_SOURCE --help' for more information.\n" >&2
+	printf "%s: unrecognized action '%s'\n\nTry '%s --help' for more information.\n" "$BL_INTERACTIVE_NAME" "$1" "$BASH_SOURCE" >&2
 	exit 2
 fi
 
diff --git a/bl-log b/bl-log
--- a/bl-log
+++ b/bl-log
@@ -17,6 +17,11 @@
 #    You should have received a copy of the GNU Lesser General Public License
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
+# shellcheck disable=SC2034 # variable appears unused
+# shellcheck disable=SC2086 # Double quote warning
+# shellcheck disable=SC2128 # expanding array without index warning
+# shellcheck disable=SC2207 # Split array warning
+
 
 if [[ "$1" == --bash-completion ]] ; then
 	_bl_log_completion()
@@ -83,7 +88,8 @@ fi
 
 ### Constants ###
 
-declare -r BL_LOG_NAME="$(basename $(readlink -f "$BASH_SOURCE") )"
+BL_LOG_NAME="$(basename "$(readlink -f "$BASH_SOURCE")" )"
+declare -r BL_LOG_NAME
 declare -r BL_LOG_VERSION="0.0.1"
 
 declare -Ar BL_LOGLEVELS=(
@@ -183,7 +189,7 @@ _bl_log_parseoptions() {
 		case "$1" in
 			-l|--log-l*) shift ; BL_LOGLEVEL="$1" ; [[ "$BL_LOGLEVEL" == [0-9] ]] || { printf "Error: log-level out of range [0-7]\n" >&2 ; return 2 ; } ;;
 			-L|--log-e*) shift ; BL_LOGEXITLNAME="$1"
-				grep -q "\<$BL_LOGEXITLNAME\>" <<<${!BL_LOGLEVELS[@]} || { printf "Error: log-exit \"$BL_LOGEXITLNAME\" is none of: ${!BL_LOGLEVELS[@]}\n" >&2 ; return 2 ; } ;;
+				grep -q "\<$BL_LOGEXITLNAME\>" <<<"${!BL_LOGLEVELS[@]}" || { printf "Error: log-exit '%s' is none of: %s\n" "$BL_LOGEXITLNAME" "${!BL_LOGLEVELS[*]}" >&2 ; return 2 ; } ;;
 			-q|--quiet) BL_LOG_O_STDERR="" ;;
 			--color|--color=on) BL_LOG_COLOR=on ;;
 			--color=off) BL_LOG_COLOR=off ;;
@@ -197,10 +203,10 @@ _bl_log_parseoptions() {
 				BL_LOGGER_OPTIONS+=("$1") ;;
 			--id*|--rfc5424*|--socket-errors*|--journald*)
 				BL_LOGGER_OPTIONS+=("$1") ;;
-			-h|--help) printf "$BL_LOG_usage\n$BL_LOG_chelpmsg\n$BL_LOG_shelpmsg\n" ; return 2 ;;
-			-V|--version) printf "$name $BL_LOG_VERSION\n" ; return 2 ;;
+			-h|--help) printf "%s\n%s\n%s\n" "$BL_LOG_usage" "$BL_LOG_chelpmsg" "$BL_LOG_shelpmsg" ; return 2 ;;
+			-V|--version) printf "%s %s\n" "$name" "$BL_LOG_VERSION" ; return 2 ;;
 			--) shift ; break ;;
-			-*) printf "$name: unrecognized option '$1'\n$BL_LOG_usage\nTry '$name --help' for more information.\n" >&2 ; return 2 ;;
+			-*) printf "%s: unrecognized option '%s'\n\nTry '%s --help' for more information.\n" "$name" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
@@ -214,16 +220,16 @@ bl_log() {
 	local -I BL_LOGLEVEL BL_LOGEXITLNAME BL_LOG_O_STDERR BL_LOGGER_OPTIONS BL_LOG_COLOR
 	local BL_LOG_helpmsg="$BL_LOG_chelpmsg"
 	_bl_log_parseoptions "$FUNCNAME" "$@" || return $?
-	[[ -n "${BL_LOG_ARGV[*]}" ]] || { echo "Error: Please give at least a priority (${!BL_LOGLEVELS[@]})" >&2 ; return 2 ; }
+	[[ -n "${BL_LOG_ARGV[*]}" ]] || { echo "Error: Please give at least a priority (${!BL_LOGLEVELS[*]})" >&2 ; return 2 ; }
 	set "${BL_LOG_ARGV[@]}"
 
 	local priority=$1 plname=${1##*.} filter
-	grep -q "\<$plname\>" <<<${!BL_LOGLEVELS[@]} || { echo "Error: priority's level name ($plname) is none of: ${!BL_LOGLEVELS[@]}" >&2 ; return 2 ; }
+	grep -q "\<$plname\>" <<<"${!BL_LOGLEVELS[@]}" || { echo "Error: priority's level name '$plname' is none of: ${!BL_LOGLEVELS[*]}" >&2 ; return 2 ; }
 	shift
 	local llevel=${BL_LOGLEVELS[$plname]}
-	if ((llevel > $BL_LOGLEVEL)) ; then
+	if ((llevel > BL_LOGLEVEL)) ; then
 		# If there is no MESSAGE, purge stdin; else do nothing.
-		[[ "$@" ]] || cat >/dev/null
+		[[ "$*" ]] || cat >/dev/null
 	else
 		if [[ "$BL_LOG_COLOR" == on ]] || [[ "$BL_LOG_COLOR" == auto ]] && [[ -t 2 ]] ; then
 			filter="2> >(sed 's,: ,: \x1b[${BL_LOGCOLORS[$llevel]}m${plname^}:\x1b[0m ,' >&2)"
diff --git a/bl-security b/bl-security
--- a/bl-security
+++ b/bl-security
@@ -16,6 +16,12 @@
 #    You should have received a copy of the GNU Lesser General Public License
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
+# shellcheck disable=SC2013 # To read lines rather than words
+# shellcheck disable=SC2034 # variable appears unused
+# shellcheck disable=SC2046 # Quote this to prevent word splitting
+# shellcheck disable=SC2086 # Double quote warning
+# shellcheck disable=SC2128 # expanding array without index warning
+
 
 if [[ "$1" == --bash-completion ]] ; then
 	BL_tmp_a="$("$BASH_SOURCE" --help | sed -n 's,^   \([a-z_-]\+\>\).*,\1,p' )"
@@ -42,7 +48,7 @@ if [[ "$1" == --bash-completion ]] ; then
 		esac
 		case $cur in
 			-*)
-				if a=$(grep -o "\<\('$(echo $BL_tmp_a | sed 's, ,\\|,g')'\)\>" <<< "${COMP_WORDS[@]}") ; then
+				if a=$(grep -o "\<\('${BL_tmp_a//$'\n'/\\|}'\)\>" <<< "${COMP_WORDS[@]}") ; then
 					COMPREPLY=( $(compgen -W "$coptions ${aoptions[$a]}" -- $cur ) )
 					return 0
 				fi
@@ -56,7 +62,7 @@ if [[ "$1" == --bash-completion ]] ; then
 			return 0
 		fi
 		# complete actions if none in ${COMP_WORDS[@]}
-		grep -q "\<\('$(echo $BL_tmp_a | sed 's, ,\\|,g')'\)\>" <<< "${COMP_WORDS[@]}" || COMPREPLY=( $(compgen -W "$actions" -- $cur ) )
+		grep -q "\<\('${BL_tmp_a//$'\n'/\\|}'\)\>" <<< "${COMP_WORDS[@]}" || COMPREPLY=( $(compgen -W "$actions" -- $cur ) )
 		return 0
 	}'
 	unset BL_tmp_a BL_tmp_o
@@ -73,21 +79,23 @@ fi
 
 ### Constants ###
 
-declare -r BL_SECURITY_NAME="$(basename $(readlink -f "$BASH_SOURCE") )"
+BL_SECURITY_NAME="$(basename "$(readlink -f "$BASH_SOURCE")" )"
+declare -r BL_SECURITY_NAME
 declare -r BL_SECURITY_VERSION="0.0.1"
 
 
 ### functions ###
 
-. $(dirname "$BASH_SOURCE")/bl-interactive --
+# shellcheck source=bl-interactive
+. "$(dirname "$BASH_SOURCE")"/bl-interactive --
 
 _bl_security_parseoptions() {
 	for ((;$#;)) ; do
 		case "$1" in
-			-h|--help) printf "$BL_SECURITY_usage\n$BL_SECURITY_chelpmsg\n$BL_SECURITY_shelpmsg\n" ; return 2 ;;
-			-V|--version) printf "$BL_SECURITY_NAME $BL_SECURITY_VERSION\n" ; return 2 ;;
+			-h|--help) printf "%s\n%s\n%s\n" "$BL_SECURITY_usage" "$BL_SECURITY_chelpmsg" "$BL_SECURITY_shelpmsg" ; return 2 ;;
+			-V|--version) printf "%s %s\n" "$BL_SECURITY_NAME" "$BL_SECURITY_VERSION" ; return 2 ;;
 			--) shift ; break ;;
-			-*) printf "$BL_SECURITY_NAME: unrecognized option '$1'\n$BL_SECURITY_usage\nTry '$BASH_SOURCE --help' for more information.\n" >&2 ; return 2 ;;
+			-*) printf "%s: unrecognized option '%s'\n\nTry '%s --help' for more information.\n" "$BL_SECURITY_NAME" "$1" "$BASH_SOURCE" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
@@ -105,20 +113,21 @@ or between 0 and (MODULO - 1) if MODULO is given.
 	for ((;$#;)) ; do
 		case "$1" in
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
-			-V|--version) echo "$FUNCNAME $PGPI_VERSION" ; return ;;
+			-V|--version) echo "$FUNCNAME $BL_SECURITY_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "$FUNCNAME: Error: unrecognized option '%s'\nTry '$name --help' for more information.\n" "$1" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
 	done
-	local m=$1 r=$(od -An -N4 -t u4 < /dev/urandom);
+	local m=$1 r
+	r=$(od -An -N4 -t u4 < /dev/urandom)
 	echo $((m?r%m:r))
 }
 
 bl_shred_path() {
 	local name
-	((BL_SECURITY_isprogram)) && name="$BL_SECURITY_NAME $(echo ${FUNCNAME:3} | tr '_' '-')" || name="$FUNCNAME"
+	((BL_SECURITY_isprogram)) && name="$BL_SECURITY_NAME $(echo "${FUNCNAME:3}" | tr '_' '-')" || name="$FUNCNAME"
 	local usage="Usage: $name [OPTIONS] PATHS..."
 	local helpmsg="
 Recursively shred all files in given path(|s).
@@ -134,28 +143,27 @@ Options:
 			-v|--verb*) varg="-v" ;;
 			-r|--remove) rmcmd="rm" ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
-			-V|--version) echo "$FUNCNAME $PGPI_VERSION" ; return ;;
+			-V|--version) echo "$FUNCNAME $BL_SECURITY_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "$FUNCNAME: Error: unrecognized option '%s'\nTry '$name --help' for more information.\n" "$1" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
 	done
-	(($#)) || { printf "$FUNCNAME: Error: no PATH given as argument\nTry '$name --help' for more information.\n" >&2 ; return 2 ; }
+	(($#)) || { printf "%s: Error: no PATH given as argument\nTry '%s --help' for more information.\n" "$FUNCNAME" "$name" >&2 ; return 2 ; }
 
-	local ifsbkp="$IFS"
-	IFS=$'\n' files=($(find "$@" -type f))
-	IFS="$ifsbkp"
+	mapfile -t files < <(find "$@" -type f)
 
 	if [[ -z "${files[*]}" ]] ; then
-		printf "$FUNCNAME: Notice: no file to shred\n" >&2
+		printf "%s: Notice: no file to shred\n" "$FUNCNAME" >&2
 	else
 		if [[ "$farg" != -f ]] ; then
-			bl_yesno -p "${files[*]}" "Shred such file(s)" || return 0
+			printf "%s\n" "${files[@]@Q}" >&2
+			bl_yesno "Shred this ${#files[@]} file(s)" || return 0
 		fi
 
 		# Don't pass $varg to shred as it use to write too many things, and moreover on stderr instead of stdin
-		! [[ "$varg" ]] || echo "shredding: ${files[@]}"
+		! [[ "$varg" ]] || echo "shredding:" "${files[@]@Q}"
 		shred $farg "${files[@]}" || return $?
 	fi
 	$rmcmd -r $farg $varg "$@" || return $?
@@ -164,7 +172,7 @@ Options:
 bl_gen_passphrase() {
 	local dict=${LANG::2} nw=3 interactive=false sedcmd sd ret
 	local name
-	((BL_SECURITY_isprogram)) && name="$BL_SECURITY_NAME $(echo ${FUNCNAME:3} | tr '_' '-')" || name="$FUNCNAME"
+	((BL_SECURITY_isprogram)) && name="$BL_SECURITY_NAME $(echo "${FUNCNAME:3}" | tr '_' '-')" || name="$FUNCNAME"
 	local usage="Usage: $name [OPTIONS]"
 	local helpmsg="
 Generate a good random passphrase
@@ -181,26 +189,27 @@ Options:
 			-D|--dict*) shift ; dict="$1" ;;
 			-n|--nword*) shift ; nw="$1" ;;
 			-h|--help) printf "%s\n%s\n" "$usage" "$helpmsg" ; return ;;
-			-V|--version) echo "$FUNCNAME $PGPI_VERSION" ; return ;;
+			-V|--version) echo "$FUNCNAME $BL_SECURITY_VERSION" ; return ;;
 			--) shift ; break ;;
-			-*) printf "$FUNCNAME: Error: unrecognized option '%s'\nTry '$name --help' for more information.\n" "$1" >&2 ; return 2 ;;
+			-*) printf "%s: Error: unrecognized option '%s'\nTry '%s --help' for more information.\n" "$FUNCNAME" "$1" "$name" >&2 ; return 2 ;;
 			*) break ;;
 		esac
 		shift
 	done
-	((! $#)) || printf "$FUNCNAME: Warning: ignoring arguments $@\n" >&2
+	((! $#)) || printf "%s: Warning: ignoring arguments %s\n" "$FUNCNAME" "$*" >&2
 
 	while ((nw-- > 0)) ; do
 		sedcmd+="\$(bl_urandom \$sd)p ; "
 	done
 
 	if $interactive ; then
-		local nd aspell_dicts=( $(aspell dump dicts | grep "^[a-z]\+$") )
+		local nd aspell_dicts
+		mapfile -t aspell_dicts < <(aspell dump dicts | grep "^[a-z]\+$")
 		nd=$(bl_chooseinlist -n 5 -p "Prefered language to generate a good passphrase ?" "${aspell_dicts[@]}")
 		((nd--))
 		dict="${aspell_dicts[$nd]}"
 	fi
-	sd=$(aspell -d "$dict" dump master | grep -v "'" | wc -l)
+	sd=$(aspell -d "$dict" dump master | grep --count --invert-match "'")
 	while true ; do
 		ret="$(aspell -d "$dict" dump master | grep -v "'" | eval sed -n \""$sedcmd"\" | tr '\n' '_')"
 		ret="${ret::-1}"
@@ -221,7 +230,7 @@ if [[ "$BASH_SOURCE" == "$0" ]] ; then
 	BL_SECURITY_usage="Usage: $BASH_SOURCE [OPTIONS]... ACTION [ACTION_ARGUMENTS]..."
 	BL_SECURITY_shelpmsg="
 Actions:
-$(for f in $(sed -n 's,^\(bl_[^(]*\)().*, \1,p' "$BASH_SOURCE") ; do printf "   %-19s%s\n" "$(echo ${f:3} | tr '_' '-')" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
+$(for f in $(sed -n 's,^\(bl_[^( ]*\) *().*, \1,p' "$BASH_SOURCE") ; do printf "   %-19s%s\n" "$(echo "${f:3}" | tr '_' '-')" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
 
 $BL_SECURITY_NAME is also bash library, see:
 $ source $BASH_SOURCE --help"
@@ -234,7 +243,7 @@ else
       --bash-completion    set completion for $BASH_SOURCE program and return (without loading anything else)
 
 Functions:
-$(for f in $(sed -n 's,^\(bl_[^(]*\)().*, \1,p' "$BASH_SOURCE") ; do printf "   %-19s%s\n" "$f" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
+$(for f in $(sed -n 's,^\(bl_[^( ]*\) *().*, \1,p' "$BASH_SOURCE") ; do printf "   %-19s%s\n" "$f" "$($f --help | sed -n '/^$/{n;p;q}')" ; done)
 
 Reminder: when used as a library, all functions calls share the same environment variables, i.e. the same global options."
 fi
@@ -256,13 +265,13 @@ _bl_security_parseoptions "$@"
 
 ### Run ###
 
-if grep -q "^bl_${1//-/_}()" "$BASH_SOURCE" ; then
+if grep -q "^bl_${1//-/_} *()" "$BASH_SOURCE" ; then
 	function="bl_${1//-/_}"
 	shift
 	$function "$@"
 	exit $?
 else
-	printf "$BL_SECURITY_NAME: unrecognized action '$1'\n$BL_SECURITY_usage\nTry '$BASH_SOURCE --help' for more information.\n" >&2
+	printf "%s: unrecognized action '%s'\n\nTry '%s --help' for more information.\n" "$BL_SECURITY_NAME" "$1" "$BASH_SOURCE" >&2
 	exit 2
 fi
 
